/**
 * Blog Post Manifest
 *
 * Static manifest of all available blog posts for Cloudflare Workers compatibility.
 * Generated from public/blog directory structure.
 */

export const blogManifest: { locale: string; slug: string }[] = [
  // English (en)
  { locale: "en", slug: "usa-cities-urban-experiences-guide" },
  { locale: "en", slug: "usa-food-culture-regional-guide" },
  { locale: "en", slug: "europe-culinary-food-guide" },
  { locale: "en", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "en", slug: "uae-dubai-attractions-guide" },
  { locale: "en", slug: "uae-desert-safari-guide" },
  { locale: "en", slug: "uk-cultural-heritage-guide" },
  { locale: "en", slug: "thailand-island-hopping-guide" },
  { locale: "en", slug: "thailand-cultural-temples-guide" },
  { locale: "en", slug: "thailand-adventure-travel-guide" },
  { locale: "en", slug: "spain-cultural-immersion-guide" },
  { locale: "en", slug: "spain-culinary-travel-guide" },
  { locale: "en", slug: "singapore-cultural-diversity-guide" },
  { locale: "en", slug: "singapore-business-travel-guide" },
  { locale: "en", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "en", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "en", slug: "japan-traditional-culture-guide" },
  { locale: "en", slug: "japan-seasonal-travel-guide" },
  { locale: "en", slug: "japan-business-travel-guide" },
  { locale: "en", slug: "india-spiritual-journey-guide" },
  { locale: "en", slug: "india-cultural-heritage-guide" },
  { locale: "en", slug: "india-adventure-travel-guide" },
  { locale: "en", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "en", slug: "germany-historical-cities-guide" },
  { locale: "en", slug: "germany-business-travel-guide" },
  { locale: "en", slug: "france-wine-regions-guide" },
  { locale: "en", slug: "france-cultural-immersion-guide" },
  { locale: "en", slug: "france-art-history-guide" },
  { locale: "en", slug: "china-modern-cities-guide" },
  { locale: "en", slug: "china-historical-heritage-guide" },
  { locale: "en", slug: "china-business-travel-guide" },
  { locale: "en", slug: "canada-national-parks-adventure-guide" },
  { locale: "en", slug: "canada-business-visa-guide" },

  // Arabic (ar)
  { locale: "ar", slug: "usa-cities-urban-experiences-guide" },
  { locale: "ar", slug: "usa-food-culture-regional-guide" },
  { locale: "ar", slug: "europe-culinary-food-guide" },
  { locale: "ar", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "ar", slug: "uae-dubai-attractions-guide" },
  { locale: "ar", slug: "uae-desert-safari-guide" },
  { locale: "ar", slug: "uk-cultural-heritage-guide" },
  { locale: "ar", slug: "thailand-island-hopping-guide" },
  { locale: "ar", slug: "thailand-cultural-temples-guide" },
  { locale: "ar", slug: "thailand-adventure-travel-guide" },
  { locale: "ar", slug: "spain-cultural-immersion-guide" },
  { locale: "ar", slug: "spain-culinary-travel-guide" },
  { locale: "ar", slug: "singapore-cultural-diversity-guide" },
  { locale: "ar", slug: "singapore-business-travel-guide" },
  { locale: "ar", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "ar", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "ar", slug: "japan-traditional-culture-guide" },
  { locale: "ar", slug: "japan-seasonal-travel-guide" },
  { locale: "ar", slug: "japan-business-travel-guide" },
  { locale: "ar", slug: "india-spiritual-journey-guide" },
  { locale: "ar", slug: "india-cultural-heritage-guide" },
  { locale: "ar", slug: "india-adventure-travel-guide" },
  { locale: "ar", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "ar", slug: "germany-historical-cities-guide" },
  { locale: "ar", slug: "germany-business-travel-guide" },
  { locale: "ar", slug: "france-wine-regions-guide" },
  { locale: "ar", slug: "france-cultural-immersion-guide" },
  { locale: "ar", slug: "france-art-history-guide" },
  { locale: "ar", slug: "china-modern-cities-guide" },
  { locale: "ar", slug: "china-historical-heritage-guide" },
  { locale: "ar", slug: "china-business-travel-guide" },
  { locale: "ar", slug: "canada-national-parks-adventure-guide" },
  { locale: "ar", slug: "canada-business-visa-guide" },

  // Spanish (es)
  { locale: "es", slug: "usa-cities-urban-experiences-guide" },
  { locale: "es", slug: "usa-food-culture-regional-guide" },
  { locale: "es", slug: "europe-culinary-food-guide" },
  { locale: "es", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "es", slug: "uae-dubai-attractions-guide" },
  { locale: "es", slug: "uae-desert-safari-guide" },
  { locale: "es", slug: "uk-cultural-heritage-guide" },
  { locale: "es", slug: "thailand-island-hopping-guide" },
  { locale: "es", slug: "thailand-cultural-temples-guide" },
  { locale: "es", slug: "thailand-adventure-travel-guide" },
  { locale: "es", slug: "spain-cultural-immersion-guide" },
  { locale: "es", slug: "spain-culinary-travel-guide" },
  { locale: "es", slug: "singapore-cultural-diversity-guide" },
  { locale: "es", slug: "singapore-business-travel-guide" },
  { locale: "es", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "es", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "es", slug: "japan-traditional-culture-guide" },
  { locale: "es", slug: "japan-seasonal-travel-guide" },
  { locale: "es", slug: "japan-business-travel-guide" },
  { locale: "es", slug: "india-spiritual-journey-guide" },
  { locale: "es", slug: "india-cultural-heritage-guide" },
  { locale: "es", slug: "india-adventure-travel-guide" },
  { locale: "es", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "es", slug: "germany-historical-cities-guide" },
  { locale: "es", slug: "germany-business-travel-guide" },
  { locale: "es", slug: "france-wine-regions-guide" },
  { locale: "es", slug: "france-cultural-immersion-guide" },
  { locale: "es", slug: "france-art-history-guide" },
  { locale: "es", slug: "china-modern-cities-guide" },
  { locale: "es", slug: "china-historical-heritage-guide" },
  { locale: "es", slug: "china-business-travel-guide" },
  { locale: "es", slug: "canada-national-parks-adventure-guide" },
  { locale: "es", slug: "canada-business-visa-guide" },
  { locale: "es", slug: "australia-adventure-travel-guide" },

  // Portuguese (pt)
  { locale: "pt", slug: "usa-cities-urban-experiences-guide" },
  { locale: "pt", slug: "usa-food-culture-regional-guide" },
  { locale: "pt", slug: "europe-culinary-food-guide" },
  { locale: "pt", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "pt", slug: "uae-dubai-attractions-guide" },
  { locale: "pt", slug: "uae-desert-safari-guide" },
  { locale: "pt", slug: "uk-cultural-heritage-guide" },
  { locale: "pt", slug: "thailand-island-hopping-guide" },
  { locale: "pt", slug: "thailand-cultural-temples-guide" },
  { locale: "pt", slug: "thailand-adventure-travel-guide" },
  { locale: "pt", slug: "spain-cultural-immersion-guide" },
  { locale: "pt", slug: "spain-culinary-travel-guide" },
  { locale: "pt", slug: "singapore-cultural-diversity-guide" },
  { locale: "pt", slug: "singapore-business-travel-guide" },
  { locale: "pt", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "pt", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "pt", slug: "japan-traditional-culture-guide" },
  { locale: "pt", slug: "japan-seasonal-travel-guide" },
  { locale: "pt", slug: "japan-business-travel-guide" },
  { locale: "pt", slug: "india-spiritual-journey-guide" },
  { locale: "pt", slug: "india-cultural-heritage-guide" },
  { locale: "pt", slug: "india-adventure-travel-guide" },
  { locale: "pt", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "pt", slug: "germany-historical-cities-guide" },
  { locale: "pt", slug: "germany-business-travel-guide" },
  { locale: "pt", slug: "france-wine-regions-guide" },
  { locale: "pt", slug: "france-cultural-immersion-guide" },
  { locale: "pt", slug: "france-art-history-guide" },
  { locale: "pt", slug: "china-modern-cities-guide" },
  { locale: "pt", slug: "china-historical-heritage-guide" },
  { locale: "pt", slug: "china-business-travel-guide" },
  { locale: "pt", slug: "canada-national-parks-adventure-guide" },
  { locale: "pt", slug: "canada-business-visa-guide" },

  // Russian (ru)
  { locale: "ru", slug: "usa-cities-urban-experiences-guide" },
  { locale: "ru", slug: "usa-food-culture-regional-guide" },
  { locale: "ru", slug: "europe-culinary-food-guide" },
  { locale: "ru", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "ru", slug: "uae-dubai-attractions-guide" },
  { locale: "ru", slug: "uae-desert-safari-guide" },
  { locale: "ru", slug: "uk-cultural-heritage-guide" },
  { locale: "ru", slug: "thailand-island-hopping-guide" },
  { locale: "ru", slug: "thailand-cultural-temples-guide" },
  { locale: "ru", slug: "thailand-adventure-travel-guide" },
  { locale: "ru", slug: "spain-cultural-immersion-guide" },
  { locale: "ru", slug: "spain-culinary-travel-guide" },
  { locale: "ru", slug: "singapore-cultural-diversity-guide" },
  { locale: "ru", slug: "singapore-business-travel-guide" },
  { locale: "ru", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "ru", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "ru", slug: "japan-traditional-culture-guide" },
  { locale: "ru", slug: "japan-seasonal-travel-guide" },
  { locale: "ru", slug: "japan-business-travel-guide" },
  { locale: "ru", slug: "india-spiritual-journey-guide" },
  { locale: "ru", slug: "india-cultural-heritage-guide" },
  { locale: "ru", slug: "india-adventure-travel-guide" },
  { locale: "ru", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "ru", slug: "germany-historical-cities-guide" },
  { locale: "ru", slug: "germany-business-travel-guide" },
  { locale: "ru", slug: "france-wine-regions-guide" },
  { locale: "ru", slug: "france-cultural-immersion-guide" },
  { locale: "ru", slug: "france-art-history-guide" },
  { locale: "ru", slug: "china-modern-cities-guide" },
  { locale: "ru", slug: "china-historical-heritage-guide" },
  { locale: "ru", slug: "china-business-travel-guide" },
  { locale: "ru", slug: "canada-national-parks-adventure-guide" },
  { locale: "ru", slug: "canada-business-visa-guide" },

  // German (de)
  { locale: "de", slug: "usa-cities-urban-experiences-guide" },
  { locale: "de", slug: "usa-food-culture-regional-guide" },
  { locale: "de", slug: "europe-culinary-food-guide" },
  { locale: "de", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "de", slug: "uae-dubai-attractions-guide" },
  { locale: "de", slug: "uae-desert-safari-guide" },
  { locale: "de", slug: "uk-cultural-heritage-guide" },
  { locale: "de", slug: "thailand-island-hopping-guide" },
  { locale: "de", slug: "thailand-cultural-temples-guide" },
  { locale: "de", slug: "thailand-adventure-travel-guide" },
  { locale: "de", slug: "spain-cultural-immersion-guide" },
  { locale: "de", slug: "spain-culinary-travel-guide" },
  { locale: "de", slug: "singapore-cultural-diversity-guide" },
  { locale: "de", slug: "singapore-business-travel-guide" },
  { locale: "de", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "de", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "de", slug: "japan-traditional-culture-guide" },
  { locale: "de", slug: "japan-seasonal-travel-guide" },
  { locale: "de", slug: "japan-business-travel-guide" },
  { locale: "de", slug: "india-spiritual-journey-guide" },
  { locale: "de", slug: "india-cultural-heritage-guide" },
  { locale: "de", slug: "india-adventure-travel-guide" },
  { locale: "de", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "de", slug: "germany-historical-cities-guide" },
  { locale: "de", slug: "germany-business-travel-guide" },
  { locale: "de", slug: "france-wine-regions-guide" },
  { locale: "de", slug: "france-cultural-immersion-guide" },
  { locale: "de", slug: "france-art-history-guide" },
  { locale: "de", slug: "china-modern-cities-guide" },
  { locale: "de", slug: "china-historical-heritage-guide" },
  { locale: "de", slug: "china-business-travel-guide" },
  { locale: "de", slug: "canada-national-parks-adventure-guide" },
  { locale: "de", slug: "canada-business-visa-guide" },

  // French (fr)
  { locale: "fr", slug: "usa-cities-urban-experiences-guide" },
  { locale: "fr", slug: "usa-food-culture-regional-guide" },
  { locale: "fr", slug: "europe-culinary-food-guide" },
  { locale: "fr", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "fr", slug: "uae-dubai-attractions-guide" },
  { locale: "fr", slug: "uae-desert-safari-guide" },
  { locale: "fr", slug: "uk-cultural-heritage-guide" },
  { locale: "fr", slug: "thailand-island-hopping-guide" },
  { locale: "fr", slug: "thailand-cultural-temples-guide" },
  { locale: "fr", slug: "thailand-adventure-travel-guide" },
  { locale: "fr", slug: "spain-cultural-immersion-guide" },
  { locale: "fr", slug: "spain-culinary-travel-guide" },
  { locale: "fr", slug: "singapore-cultural-diversity-guide" },
  { locale: "fr", slug: "singapore-business-travel-guide" },
  { locale: "fr", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "fr", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "fr", slug: "japan-traditional-culture-guide" },
  { locale: "fr", slug: "japan-seasonal-travel-guide" },
  { locale: "fr", slug: "japan-business-travel-guide" },
  { locale: "fr", slug: "india-spiritual-journey-guide" },
  { locale: "fr", slug: "india-cultural-heritage-guide" },
  { locale: "fr", slug: "india-adventure-travel-guide" },
  { locale: "fr", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "fr", slug: "germany-historical-cities-guide" },
  { locale: "fr", slug: "germany-business-travel-guide" },
  { locale: "fr", slug: "france-wine-regions-guide" },
  { locale: "fr", slug: "france-cultural-immersion-guide" },
  { locale: "fr", slug: "france-art-history-guide" },
  { locale: "fr", slug: "china-modern-cities-guide" },
  { locale: "fr", slug: "china-historical-heritage-guide" },
  { locale: "fr", slug: "china-business-travel-guide" },
  { locale: "fr", slug: "canada-national-parks-adventure-guide" },
  { locale: "fr", slug: "canada-business-visa-guide" },

  // Italian (it)
  { locale: "it", slug: "usa-cities-urban-experiences-guide" },
  { locale: "it", slug: "usa-food-culture-regional-guide" },
  { locale: "it", slug: "europe-culinary-food-guide" },
  { locale: "it", slug: "saudi-arabia-cultural-desert-adventures" },
  { locale: "it", slug: "uae-dubai-attractions-guide" },
  { locale: "it", slug: "uae-desert-safari-guide" },
  { locale: "it", slug: "uk-cultural-heritage-guide" },
  { locale: "it", slug: "thailand-island-hopping-guide" },
  { locale: "it", slug: "thailand-cultural-temples-guide" },
  { locale: "it", slug: "thailand-adventure-travel-guide" },
  { locale: "it", slug: "spain-cultural-immersion-guide" },
  { locale: "it", slug: "spain-culinary-travel-guide" },
  { locale: "it", slug: "singapore-cultural-diversity-guide" },
  { locale: "it", slug: "singapore-business-travel-guide" },
  { locale: "it", slug: "saudi-arabia-vision-2030-tourism-guide" },
  { locale: "it", slug: "saudi-arabia-business-opportunities-guide" },
  { locale: "it", slug: "japan-traditional-culture-guide" },
  { locale: "it", slug: "japan-seasonal-travel-guide" },
  { locale: "it", slug: "japan-business-travel-guide" },
  { locale: "it", slug: "india-spiritual-journey-guide" },
  { locale: "it", slug: "india-cultural-heritage-guide" },
  { locale: "it", slug: "india-adventure-travel-guide" },
  { locale: "it", slug: "germany-oktoberfest-cultural-guide" },
  { locale: "it", slug: "germany-historical-cities-guide" },
  { locale: "it", slug: "germany-business-travel-guide" },
  { locale: "it", slug: "france-wine-regions-guide" },
  { locale: "it", slug: "france-cultural-immersion-guide" },
  { locale: "it", slug: "france-art-history-guide" },
  { locale: "it", slug: "china-modern-cities-guide" },
  { locale: "it", slug: "china-historical-heritage-guide" },
  { locale: "it", slug: "china-business-travel-guide" },
  { locale: "it", slug: "canada-national-parks-adventure-guide" },
  { locale: "it", slug: "canada-business-visa-guide" },
];

/**
 * Get all blog posts for a specific locale
 */
export function getBlogPostsForLocale(
  locale: string
): { locale: string; slug: string }[] {
  return blogManifest.filter(post => post.locale === locale);
}

/**
 * Get all blog posts across all locales
 */
export function getAllBlogPosts(): { locale: string; slug: string }[] {
  return blogManifest;
}

/**
 * Check if a blog post exists for a given locale and slug
 */
export function blogPostExists(locale: string, slug: string): boolean {
  return blogManifest.some(
    post => post.locale === locale && post.slug === slug
  );
}
