// Fallback data for development when database is not available
export const fallbackDestinations = [
  {
    id: 1,
    code: "AE",
    name: "United Arab Emirates",
    nameAr: "دولة الإمارات العربية المتحدة",
    flag: "🇦🇪",
    region: "Middle East",
    capital: "Abu Dhabi",
    capitalAr: "أبوظبي",
    description:
      "A federation of seven emirates known for modern cities, luxury shopping, and rich cultural heritage.",
    descriptionAr: "اتحاد سبع إمارات معروف بالمدن الحديثة والتسوق الفاخر والتراث الثقافي الغني.",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    code: "US",
    name: "United States",
    nameAr: "الولايات المتحدة الأمريكية",
    flag: "🇺🇸",
    region: "North America",
    capital: "Washington D.C.",
    capitalAr: "واشنطن العاصمة",
    description: "A diverse country known for innovation, culture, and economic opportunities.",
    descriptionAr: "دولة متنوعة معروفة بالابتكار والثقافة والفرص الاقتصادية.",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    code: "GB",
    name: "United Kingdom",
    nameAr: "المملكة المتحدة",
    flag: "🇬🇧",
    region: "Europe",
    capital: "London",
    capitalAr: "لندن",
    description:
      "Historic nation known for its cultural heritage, education, and business opportunities.",
    descriptionAr: "دولة تاريخية معروفة بتراثها الثقافي والتعليم والفرص التجارية.",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    code: "CA",
    name: "Canada",
    nameAr: "كندا",
    flag: "🇨🇦",
    region: "North America",
    capital: "Ottawa",
    capitalAr: "أوتاوا",
    description: "Friendly nation known for natural beauty, multiculturalism, and quality of life.",
    descriptionAr: "دولة ودودة معروفة بالجمال الطبيعي والتعددية الثقافية وجودة الحياة.",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const fallbackPassportCountries = [
  {
    id: 1,
    code: "EG",
    name: "Egypt",
    nameAr: "مصر",
    flag: "🇪🇬",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    code: "SA",
    name: "Saudi Arabia",
    nameAr: "المملكة العربية السعودية",
    flag: "🇸🇦",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    code: "IN",
    name: "India",
    nameAr: "الهند",
    flag: "🇮🇳",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    code: "PK",
    name: "Pakistan",
    nameAr: "باكستان",
    flag: "🇵🇰",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const fallbackArticles = [
  {
    id: 1,
    destinationId: 1,
    title: "Complete Guide to UAE Visa Requirements",
    titleAr: "الدليل الشامل لمتطلبات التأشيرة الإماراتية",
    slug: "uae-visa-requirements-guide",
    content:
      "<p>The UAE offers various visa options for tourists, business visitors, and residents. This comprehensive guide covers everything you need to know about UAE visa requirements, application processes, and tips for a successful application.</p>",
    contentAr:
      "<p>تقدم دولة الإمارات العربية المتحدة خيارات تأشيرة متنوعة للسياح وزوار الأعمال والمقيمين. يغطي هذا الدليل الشامل كل ما تحتاج لمعرفته حول متطلبات التأشيرة الإماراتية وعمليات التقديم ونصائح للحصول على تطبيق ناجح.</p>",
    excerpt: "Everything you need to know about UAE visa requirements and application process.",
    excerptAr: "كل ما تحتاج لمعرفته حول متطلبات التأشيرة الإماراتية وعملية التقديم.",
    featuredImage:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=400&fit=crop",
    author: "Visa Expert Team",
    isPublished: true,
    publishedAt: "2024-01-15T10:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    destinationName: "United Arab Emirates",
    destinationNameAr: "دولة الإمارات العربية المتحدة",
    destinationFlag: "🇦🇪",
  },
  {
    id: 2,
    destinationId: 2,
    title: "US Tourist Visa Application Process",
    titleAr: "عملية تقديم طلب التأشيرة السياحية الأمريكية",
    slug: "us-tourist-visa-application",
    content:
      "<p>Applying for a US tourist visa requires careful preparation and documentation. This guide walks you through the B-1/B-2 visa application process, required documents, and interview tips.</p>",
    contentAr:
      "<p>يتطلب التقدم بطلب للحصول على تأشيرة سياحية أمريكية إعداداً دقيقاً ووثائق. يرشدك هذا الدليل خلال عملية التقدم للحصول على تأشيرة B-1/B-2 والوثائق المطلوبة ونصائح المقابلة.</p>",
    excerpt: "Complete guide to applying for US tourist visa with step-by-step instructions.",
    excerptAr:
      "دليل كامل للتقدم بطلب للحصول على التأشيرة السياحية الأمريكية مع تعليمات خطوة بخطوة.",
    featuredImage:
      "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800&h=400&fit=crop",
    author: "Immigration Specialist",
    isPublished: true,
    publishedAt: "2024-01-10T14:30:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    destinationName: "United States",
    destinationNameAr: "الولايات المتحدة الأمريكية",
    destinationFlag: "🇺🇸",
  },
];

export const fallbackVisaTypes = [
  {
    id: 1,
    destinationId: 1,
    name: "Tourist Visa",
    nameAr: "تأشيرة سياحية",
    slug: "tourist-visa",
    description: "Short-term visa for tourism and leisure travel",
    descriptionAr: "تأشيرة قصيرة الأمد للسياحة والسفر الترفيهي",
    fee: 100,
    currency: "USD",
    processingTime: "3-5 business days",
    processingTimeAr: "3-5 أيام عمل",
    validity: "30 days",
    validityAr: "30 يوم",
    entryType: "single",
    requirements: '["Valid passport", "Passport photos", "Travel itinerary"]',
    requirementsAr: '["جواز سفر ساري", "صور جواز السفر", "مسار الرحلة"]',
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    destinationId: 1,
    name: "Business Visa",
    nameAr: "تأشيرة عمل",
    slug: "business-visa",
    description: "For business meetings, conferences, and trade activities",
    descriptionAr: "للاجتماعات التجارية والمؤتمرات والأنشطة التجارية",
    fee: 150,
    currency: "USD",
    processingTime: "5-7 business days",
    processingTimeAr: "5-7 أيام عمل",
    validity: "90 days",
    validityAr: "90 يوم",
    entryType: "multiple",
    requirements: '["Valid passport", "Business invitation", "Company letter"]',
    requirementsAr: '["جواز سفر ساري", "دعوة عمل", "خطاب من الشركة"]',
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];
