CREATE TABLE `countries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`code` text(3) NOT NULL,
	`name_en` text NOT NULL,
	`name_ar` text,
	`name_es` text,
	`name_pt` text,
	`name_ru` text,
	`name_de` text,
	`name_fr` text,
	`name_it` text,
	`description_en` text,
	`description_ar` text,
	`description_es` text,
	`description_pt` text,
	`description_ru` text,
	`description_de` text,
	`description_fr` text,
	`description_it` text,
	`flag` text,
	`continent` text NOT NULL,
	`region` text,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`deleted_at` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `countries_code_unique` ON `countries` (`code`);--> statement-breakpoint
CREATE TABLE `visa_eligibility` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`destination_id` integer NOT NULL,
	`passport_id` integer NOT NULL,
	`visa_type_id` integer NOT NULL,
	`eligibility_status` text NOT NULL,
	`max_stay_days` integer,
	`notes_en` text,
	`notes_ar` text,
	`notes_es` text,
	`notes_pt` text,
	`notes_ru` text,
	`notes_de` text,
	`notes_fr` text,
	`notes_it` text,
	`last_updated` integer DEFAULT (unixepoch()) NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`destination_id`) REFERENCES `countries`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`passport_id`) REFERENCES `countries`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`visa_type_id`) REFERENCES `visa_types`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `visa_types` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`destination_id` integer NOT NULL,
	`type` text NOT NULL,
	`name_en` text NOT NULL,
	`name_ar` text,
	`name_es` text,
	`name_pt` text,
	`name_ru` text,
	`name_de` text,
	`name_fr` text,
	`name_it` text,
	`description_en` text,
	`description_ar` text,
	`description_es` text,
	`description_pt` text,
	`description_ru` text,
	`description_de` text,
	`description_fr` text,
	`description_it` text,
	`duration` integer NOT NULL,
	`max_stay` integer,
	`processing_time` integer NOT NULL,
	`fee` real NOT NULL,
	`currency` text DEFAULT 'USD' NOT NULL,
	`requires_interview` integer DEFAULT false NOT NULL,
	`is_multi_entry` integer DEFAULT false NOT NULL,
	`requirements` text,
	`documents` text,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`deleted_at` integer,
	FOREIGN KEY (`destination_id`) REFERENCES `countries`(`id`) ON UPDATE no action ON DELETE no action
);
