-- Insert blog tags data with conflict resolution
-- Total blog tags: 152
INSERT INTO blog_tags (slug, name, created_at, updated_at) VALUES
('business-visa', 'Business visa', now(), now()),
('entrepreneurship', 'Entrepreneurship', now(), now()),
('immigration', 'Immigration', now(), now()),
('business-travel', 'Business travel', now(), now()),
('visa-application', 'Visa application', now(), now()),
('business-immigration', 'Business immigration', now(), now()),
('professional-travel', 'Professional travel', now(), now()),
('national-parks', 'National parks', now(), now()),
('outdoor-adventure', 'Outdoor adventure', now(), now()),
('nature', 'Nature', now(), now()),
('hiking', 'Hiking', now(), now()),
('wilderness-exploration', 'Wilderness exploration', now(), now()),
('outdoor-activities', 'Outdoor activities', now(), now()),
('nature-tourism', 'Nature tourism', now(), now()),
('visitor-visa', 'Visitor visa', now(), now()),
('travel', 'Travel', now(), now()),
('travel-planning', 'Travel planning', now(), now()),
('visa-requirements', 'Visa requirements', now(), now()),
('tourism', 'Tourism', now(), now()),
('winter-activities', 'Winter activities', now(), now()),
('skiing', 'Skiing', now(), now()),
('northern-lights', 'Northern lights', now(), now()),
('winter-sports', 'Winter sports', now(), now()),
('cold-weather-adventures', 'Cold weather adventures', now(), now()),
('winter-tourism', 'Winter tourism', now(), now()),
('culinary-culture', 'Culinary culture', now(), now()),
('regional-cuisines', 'Regional cuisines', now(), now()),
('food-culture', 'Food culture', now(), now()),
('european-cuisine', 'European cuisine', now(), now()),
('traditional-dishes', 'Traditional dishes', now(), now()),
('culinary-traditions', 'Culinary traditions', now(), now()),
('food-experiences', 'Food experiences', now(), now()),
('cultural-museums', 'Cultural museums', now(), now()),
('art-museums', 'Art museums', now(), now()),
('history-museums', 'History museums', now(), now()),
('cultural-heritage', 'Cultural heritage', now(), now()),
('museum-guide', 'Museum guide', now(), now()),
('cultural-institutions', 'Cultural institutions', now(), now()),
('art-collections', 'Art collections', now(), now()),
('festivals', 'Festivals', now(), now()),
('seasonal-events', 'Seasonal events', now(), now()),
('cultural-celebrations', 'Cultural celebrations', now(), now()),
('seasonal-experiences', 'Seasonal experiences', now(), now()),
('cultural-events', 'Cultural events', now(), now()),
('festival-culture', 'Festival culture', now(), now()),
('seasonal-travel', 'Seasonal travel', now(), now()),
('transportation', 'Transportation', now(), now()),
('travel-tips', 'Travel tips', now(), now()),
('european-travel', 'European travel', now(), now()),
('public-transport', 'Public transport', now(), now()),
('transportation-guide', 'Transportation guide', now(), now()),
('european-transport', 'European transport', now(), now()),
('cultural-experiences', 'Cultural experiences', now(), now()),
('traditional-culture', 'Traditional culture', now(), now()),
('cultural-traditions', 'Cultural traditions', now(), now()),
('travel-guide', 'Travel guide', now(), now()),
('cultural-immersion', 'Cultural immersion', now(), now()),
('traditional-arts', 'Traditional arts', now(), now()),
('cuisine', 'Cuisine', now(), now()),
('regional-specialties', 'Regional specialties', now(), now()),
('asian-cuisine', 'Asian cuisine', now(), now()),
('dining-experiences', 'Dining experiences', now(), now()),
('tourist-visa', 'Tourist visa', now(), now()),
('asia', 'Asia', now(), now()),
('city-attractions', 'City attractions', now(), now()),
('hidden-gems', 'Hidden gems', now(), now()),
('landmarks', 'Landmarks', now(), now()),
('sightseeing', 'Sightseeing', now(), now()),
('city-tours', 'City tours', now(), now()),
('tourist-destinations', 'Tourist destinations', now(), now()),
('urban-exploration', 'Urban exploration', now(), now()),
('europe', 'Europe', now(), now()),
('multi-destination', 'Multi destination', now(), now()),
('visas', 'Visas', now(), now()),
('multi-country-travel', 'Multi country travel', now(), now()),
('travel-itineraries', 'Travel itineraries', now(), now()),
('cultural-adventures', 'Cultural adventures', now(), now()),
('desert-experiences', 'Desert experiences', now(), now()),
('traditional-activities', 'Traditional activities', now(), now()),
('desert-culture', 'Desert culture', now(), now()),
('cultural-tourism', 'Cultural tourism', now(), now()),
('historical-sites', 'Historical sites', now(), now()),
('archaeological-wonders', 'Archaeological wonders', now(), now()),
('ancient-ruins', 'Ancient ruins', now(), now()),
('historical-treasures', 'Historical treasures', now(), now()),
('cultural-sites', 'Cultural sites', now(), now()),
('archaeological-sites', 'Archaeological sites', now(), now()),
('modern-cities', 'Modern cities', now(), now()),
('urban-development', 'Urban development', now(), now()),
('contemporary-culture', 'Contemporary culture', now(), now()),
('urban-experiences', 'Urban experiences', now(), now()),
('city-life', 'City life', now(), now()),
('urban-culture', 'Urban culture', now(), now()),
('metropolitan-development', 'Metropolitan development', now(), now()),
('tourism-development', 'Tourism development', now(), now()),
('future-travel', 'Future travel', now(), now()),
('development-plans', 'Development plans', now(), now()),
('tourism-transformation', 'Tourism transformation', now(), now()),
('future-attractions', 'Future attractions', now(), now()),
('tourism-initiatives', 'Tourism initiatives', now(), now()),
('development-projects', 'Development projects', now(), now()),
('schengen', 'Schengen', now(), now()),
('multiple-countries', 'Multiple countries', now(), now()),
('international-travel', 'International travel', now(), now()),
('highland-adventures', 'Highland adventures', now(), now()),
('scottish-culture', 'Scottish culture', now(), now()),
('natural-wonders', 'Natural wonders', now(), now()),
('arts', 'Arts', now(), now()),
('heritage-sites', 'Heritage sites', now(), now()),
('museums', 'Museums', now(), now()),
('desert-adventures', 'Desert adventures', now(), now()),
('desert-safaris', 'Desert safaris', now(), now()),
('camping', 'Camping', now(), now()),
('adventure-travel', 'Adventure travel', now(), now()),
('outdoor-adventures', 'Outdoor adventures', now(), now()),
('urban-adventures', 'Urban adventures', now(), now()),
('emirati-cuisine', 'Emirati cuisine', now(), now()),
('middle-eastern-food', 'Middle eastern food', now(), now()),
('fine-dining', 'Fine dining', now(), now()),
('historic-sites', 'Historic sites', now(), now()),
('traditions', 'Traditions', now(), now()),
('british-culture', 'British culture', now(), now()),
('historic-preservation', 'Historic preservation', now(), now()),
('traditional-pubs', 'Traditional pubs', now(), now()),
('british-cuisine', 'British cuisine', now(), now()),
('pub-food', 'Pub food', now(), now()),
('traditional-dining', 'Traditional dining', now(), now()),
('british-traditions', 'British traditions', now(), now()),
('travel-documents', 'Travel documents', now(), now()),
('application-process', 'Application process', now(), now()),
('metropolitan-adventures', 'Metropolitan adventures', now(), now()),
('cultural-attractions', 'Cultural attractions', now(), now()),
('metropolitan-travel', 'Metropolitan travel', now(), now()),
('regional-cuisine', 'Regional cuisine', now(), now()),
('comfort-food', 'Comfort food', now(), now()),
('seafood', 'Seafood', now(), now()),
('barbecue', 'Barbecue', now(), now()),
('wilderness', 'Wilderness', now(), now()),
('wildlife-viewing', 'Wildlife viewing', now(), now()),
('nature-exploration', 'Nature exploration', now(), now()),
('road-trip', 'Road trip', now(), now()),
('scenic-routes', 'Scenic routes', now(), now()),
('highway-adventures', 'Highway adventures', now(), now()),
('cross-country', 'Cross country', now(), now()),
('b2-visa', 'B2 visa', now(), now()),
('visa-turista', 'Visa turista', now(), now()),
('visa-b2', 'Visa b2', now(), now()),
('turismo', 'Turismo', now(), now()),
('viajes', 'Viajes', now(), now()),
('aplicacion-visa', 'Aplicacion visa', now(), now()),
('requisitos-visa', 'Requisitos visa', now(), now()),
('planificacion-viaje', 'Planificacion viaje', now(), now())
ON CONFLICT (slug) DO NOTHING;