-- Insert blog posts i18n data with conflict resolution
-- Supporting multiple languages for key blog posts
INSERT INTO blog_posts_i18n (post_id, locale, title, description, content, meta_keywords, created_at, updated_at) VALUES
-- Canada Business Visa Guide
((SELECT id FROM blog_posts WHERE slug = 'canada-business-visa-guide'), 'en', 'Canada Business Visa Guide: Complete Application Process', 'Everything you need to know about applying for a Canadian business visa, including requirements, documents, and processing times.', 'A comprehensive guide to obtaining a business visa for Canada, covering eligibility criteria, required documentation, and step-by-step application process. Learn about different visa types, processing times, and tips for successful applications.', 'canada business visa, work permit, immigration, professional visa', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'canada-business-visa-guide'), 'ar', 'دليل فيزا الأعمال الكندية: عملية التقديم الكاملة', 'كل ما تحتاج لمعرفته حول التقديم للحصول على فيزا الأعمال الكندية، بما في ذلك المتطلبات والوثائق وأوقات المعالجة.', 'دليل شامل للحصول على فيزا الأعمال في كندا، يغطي معايير الأهلية والوثائق المطلوبة وعملية التقديم خطوة بخطوة.', 'فيزا أعمال كندا, تصريح عمل, هجرة, فيزا مهنية', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'canada-business-visa-guide'), 'es', 'Guía de Visa de Negocios de Canadá: Proceso Completo de Solicitud', 'Todo lo que necesitas saber sobre la solicitud de una visa de negocios canadiense, incluyendo requisitos, documentos y tiempos de procesamiento.', 'Una guía completa para obtener una visa de negocios para Canadá, cubriendo criterios de elegibilidad, documentación requerida y proceso de solicitud paso a paso.', 'visa de negocios canadá, permiso de trabajo, inmigración, visa profesional', now(), now()),

-- Canada Visitor Visa Guide
((SELECT id FROM blog_posts WHERE slug = 'canada-visitor-visa-guide'), 'en', 'Canada Visitor Visa Guide: Tourist Application Made Easy', 'Step-by-step guide to applying for a Canadian tourist visa, including requirements, fees, and processing times for visitors.', 'Complete guide for tourists planning to visit Canada, including visa requirements, application process, and travel tips for a successful trip.', 'canada tourist visa, visitor visa, travel to canada, tourism', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'canada-visitor-visa-guide'), 'ar', 'دليل فيزا الزائر الكندية: تطبيق السياحة مبسط', 'دليل خطوة بخطوة للتقديم للحصول على فيزا سياحية كندية، بما في ذلك المتطلبات والرسوم وأوقات المعالجة للزوار.', 'دليل كامل للسياح الذين يخططون لزيارة كندا، بما في ذلك متطلبات الفيزا وعملية التقديم ونصائح السفر.', 'فيزا سياحية كندا, فيزا زائر, السفر إلى كندا, سياحة', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'canada-visitor-visa-guide'), 'es', 'Guía de Visa de Visitante de Canadá: Solicitud Turística Simplificada', 'Guía paso a paso para solicitar una visa turística canadiense, incluyendo requisitos, tarifas y tiempos de procesamiento para visitantes.', 'Guía completa para turistas que planean visitar Canadá, incluyendo requisitos de visa, proceso de solicitud y consejos de viaje.', 'visa turística canadá, visa de visitante, viajar a canadá, turismo', now(), now()),

-- UAE Dubai Attractions Guide
((SELECT id FROM blog_posts WHERE slug = 'uae-dubai-attractions-guide'), 'en', 'UAE Dubai Attractions Guide: Must-Visit Places', 'Discover the top attractions and experiences in Dubai, UAE, from modern skyscrapers to traditional souks and desert adventures.', 'Explore Dubai''s iconic landmarks, luxury shopping, cultural sites, and unique experiences in this comprehensive travel guide to the UAE''s most famous city.', 'dubai attractions, uae tourism, travel guide, middle east travel', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'uae-dubai-attractions-guide'), 'ar', 'دليل معالم دبي الإمارات: الأماكن التي يجب زيارتها', 'اكتشف أهم المعالم والتجارب في دبي، الإمارات العربية المتحدة، من ناطحات السحاب الحديثة إلى الأسواق التقليدية ومغامرات الصحراء.', 'استكشف معالم دبي الأيقونية والتسوق الفاخر والمواقع الثقافية والتجارب الفريدة في هذا الدليل الشامل للسفر إلى أشهر مدن الإمارات.', 'معالم دبي, سياحة الإمارات, دليل السفر, سفر الشرق الأوسط', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'uae-dubai-attractions-guide'), 'es', 'Guía de Atracciones de Dubai EAU: Lugares Imprescindibles', 'Descubre las principales atracciones y experiencias en Dubai, EAU, desde rascacielos modernos hasta zocos tradicionales y aventuras en el desierto.', 'Explora los monumentos icónicos de Dubai, compras de lujo, sitios culturales y experiencias únicas en esta guía completa de viaje a la ciudad más famosa de los EAU.', 'atracciones dubai, turismo eau, guía de viaje, viaje medio oriente', now(), now()),

-- Japan Business Visa Guide
((SELECT id FROM blog_posts WHERE slug = 'japan-business-visa-guide'), 'en', 'Japan Business Visa Guide: Professional Travel Requirements', 'Complete guide to obtaining a business visa for Japan, including application requirements, documentation, and processing procedures.', 'Everything professionals need to know about applying for a Japanese business visa, from eligibility requirements to approval and travel planning.', 'japan business visa, work visa, professional travel, business immigration', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'japan-business-visa-guide'), 'ar', 'دليل فيزا الأعمال اليابانية: متطلبات السفر المهني', 'دليل كامل للحصول على فيزا الأعمال لليابان، بما في ذلك متطلبات التقديم والوثائق وإجراءات المعالجة.', 'كل ما يحتاج المهنيون لمعرفته حول التقديم للحصول على فيزا الأعمال اليابانية، من متطلبات الأهلية إلى الموافقة وتخطيط السفر.', 'فيزا أعمال اليابان, فيزا عمل, سفر مهني, هجرة أعمال', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'japan-business-visa-guide'), 'es', 'Guía de Visa de Negocios de Japón: Requisitos de Viaje Profesional', 'Guía completa para obtener una visa de negocios para Japón, incluyendo requisitos de solicitud, documentación y procedimientos de procesamiento.', 'Todo lo que los profesionales necesitan saber sobre la solicitud de una visa de negocios japonesa, desde requisitos de elegibilidad hasta aprobación y planificación de viaje.', 'visa de negocios japón, visa de trabajo, viaje profesional, inmigración de negocios', now(), now()),

-- Japan Tourist Visa Guide
((SELECT id FROM blog_posts WHERE slug = 'japan-tourist-visa-guide'), 'en', 'Japan Tourist Visa Guide: Visiting the Land of the Rising Sun', 'Comprehensive guide to applying for a Japanese tourist visa, including requirements, fees, and travel planning tips.', 'Plan your trip to Japan with this complete visa guide covering application process, requirements, and travel recommendations for an unforgettable experience.', 'japan tourist visa, visit japan, travel guide, japanese tourism', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'japan-tourist-visa-guide'), 'ar', 'دليل فيزا السياحة اليابانية: زيارة بلد الشمس المشرقة', 'دليل شامل للتقديم للحصول على فيزا سياحية يابانية، بما في ذلك المتطلبات والرسوم ونصائح تخطيط السفر.', 'خطط لرحلتك إلى اليابان مع هذا الدليل الكامل للفيزا الذي يغطي عملية التقديم والمتطلبات وتوصيات السفر لتجربة لا تُنسى.', 'فيزا سياحية اليابان, زيارة اليابان, دليل السفر, سياحة يابانية', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'japan-tourist-visa-guide'), 'es', 'Guía de Visa Turística de Japón: Visitando la Tierra del Sol Naciente', 'Guía completa para solicitar una visa turística japonesa, incluyendo requisitos, tarifas y consejos de planificación de viaje.', 'Planifica tu viaje a Japón con esta guía completa de visa que cubre el proceso de solicitud, requisitos y recomendaciones de viaje para una experiencia inolvidable.', 'visa turística japón, visitar japón, guía de viaje, turismo japonés', now(), now()),

-- Schengen Visa Requirements
((SELECT id FROM blog_posts WHERE slug = 'schengen-visa-requirements'), 'en', 'Schengen Visa Requirements: Travel Multiple European Countries', 'Complete guide to Schengen visa application, allowing travel to 26 European countries with a single visa.', 'Everything you need to know about applying for a Schengen visa, including requirements, documentation, and travel benefits across Europe.', 'schengen visa, europe travel, european union, multi-country visa', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'schengen-visa-requirements'), 'ar', 'متطلبات فيزا شنغن: السفر إلى عدة دول أوروبية', 'دليل كامل لتطبيق فيزا شنغن، يسمح بالسفر إلى 26 دولة أوروبية بفيزا واحدة.', 'كل ما تحتاج لمعرفته حول التقديم للحصول على فيزا شنغن، بما في ذلك المتطلبات والوثائق وفوائد السفر عبر أوروبا.', 'فيزا شنغن, سفر أوروبا, الاتحاد الأوروبي, فيزا متعددة البلدان', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'schengen-visa-requirements'), 'es', 'Requisitos de Visa Schengen: Viajar a Múltiples Países Europeos', 'Guía completa para la solicitud de visa Schengen, permitiendo viajar a 26 países europeos con una sola visa.', 'Todo lo que necesitas saber sobre la solicitud de una visa Schengen, incluyendo requisitos, documentación y beneficios de viaje por Europa.', 'visa schengen, viaje europa, unión europea, visa multi-país', now(), now()),

-- UK Visa Application Tips
((SELECT id FROM blog_posts WHERE slug = 'uk-visa-application-tips'), 'en', 'UK Visa Application Tips: Successful British Visa Guide', 'Expert tips and guidance for applying for UK visas, including common mistakes to avoid and application best practices.', 'Increase your chances of UK visa approval with these professional tips and comprehensive application guidance for various visa types.', 'uk visa, british visa, visa application tips, united kingdom travel', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'uk-visa-application-tips'), 'ar', 'نصائح تطبيق فيزا المملكة المتحدة: دليل الفيزا البريطانية الناجحة', 'نصائح خبراء وإرشادات للتقديم للحصول على فيز المملكة المتحدة، بما في ذلك الأخطاء الشائعة التي يجب تجنبها وأفضل ممارسات التطبيق.', 'زد من فرص موافقة فيزا المملكة المتحدة مع هذه النصائح المهنية والإرشادات الشاملة للتطبيق لأنواع الفيز المختلفة.', 'فيزا المملكة المتحدة, فيزا بريطانية, نصائح تطبيق فيزا, سفر المملكة المتحدة', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'uk-visa-application-tips'), 'es', 'Consejos de Solicitud de Visa del Reino Unido: Guía Exitosa de Visa Británica', 'Consejos de expertos y orientación para solicitar visas del Reino Unido, incluyendo errores comunes a evitar y mejores prácticas de solicitud.', 'Aumenta tus posibilidades de aprobación de visa del Reino Unido con estos consejos profesionales y orientación integral de solicitud para varios tipos de visa.', 'visa reino unido, visa británica, consejos solicitud visa, viaje reino unido', now(), now()),

-- USA Tourist Visa B-2 Guide
((SELECT id FROM blog_posts WHERE slug = 'usa-tourist-visa-b2-guide'), 'en', 'USA Tourist Visa B-2 Guide: Visit America Successfully', 'Complete guide to applying for a US B-2 tourist visa, including requirements, interview preparation, and approval tips.', 'Everything you need to know about obtaining a US tourist visa, from application to approval and travel planning for your American adventure.', 'usa tourist visa, b2 visa, america travel, us visa application', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'usa-tourist-visa-b2-guide'), 'ar', 'دليل فيزا السياحة الأمريكية B-2: زيارة أمريكا بنجاح', 'دليل كامل للتقديم للحصول على فيزا سياحية أمريكية B-2، بما في ذلك المتطلبات وإعداد المقابلة ونصائح الموافقة.', 'كل ما تحتاج لمعرفته حول الحصول على فيزا سياحية أمريكية، من التطبيق إلى الموافقة وتخطيط السفر لمغامرتك الأمريكية.', 'فيزا سياحية أمريكية, فيزا B2, سفر أمريكا, تطبيق فيزا أمريكية', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'usa-tourist-visa-b2-guide'), 'es', 'Guía de Visa Turística USA B-2: Visita América Exitosamente', 'Guía completa para solicitar una visa turística estadounidense B-2, incluyendo requisitos, preparación de entrevista y consejos de aprobación.', 'Todo lo que necesitas saber sobre obtener una visa turística estadounidense, desde la solicitud hasta la aprobación y planificación de viaje para tu aventura americana.', 'visa turística usa, visa b2, viaje américa, solicitud visa estadounidense', now(), now()),

-- Europe Culinary Food Guide
((SELECT id FROM blog_posts WHERE slug = 'europe-culinary-food-guide'), 'en', 'Europe Culinary Food Guide: Taste the Continent', 'Discover the diverse culinary traditions across Europe, from French cuisine to Italian pasta and German specialties.', 'A food lover''s guide to European cuisine, featuring traditional dishes, food culture, and culinary experiences across the continent.', 'european cuisine, food culture, culinary travel, traditional dishes', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'europe-culinary-food-guide'), 'ar', 'دليل الطعام الأوروبي: تذوق القارة', 'اكتشف التقاليد الطهوية المتنوعة عبر أوروبا، من المطبخ الفرنسي إلى المعكرونة الإيطالية والتخصصات الألمانية.', 'دليل محب الطعام للمطبخ الأوروبي، يضم الأطباق التقليدية وثقافة الطعام والتجارب الطهوية عبر القارة.', 'مطبخ أوروبي, ثقافة الطعام, سفر طهوي, أطباق تقليدية', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'europe-culinary-food-guide'), 'es', 'Guía Culinaria de Europa: Saborea el Continente', 'Descubre las diversas tradiciones culinarias de Europa, desde la cocina francesa hasta la pasta italiana y especialidades alemanas.', 'Una guía para amantes de la comida sobre la cocina europea, presentando platos tradicionales, cultura gastronómica y experiencias culinarias por todo el continente.', 'cocina europea, cultura gastronómica, viaje culinario, platos tradicionales', now(), now()),

-- Saudi Arabia Modern Cities Guide
((SELECT id FROM blog_posts WHERE slug = 'saudi-arabia-modern-cities-guide'), 'en', 'Saudi Arabia Modern Cities Guide: Vision 2030 Development', 'Explore Saudi Arabia''s modern urban development and futuristic cities as part of the ambitious Vision 2030 program.', 'Discover the transformation of Saudi Arabian cities, from NEOM to Riyadh, showcasing modern architecture and urban innovation under Vision 2030.', 'saudi arabia cities, vision 2030, modern development, middle east tourism', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'saudi-arabia-modern-cities-guide'), 'ar', 'دليل المدن الحديثة في السعودية: تطوير رؤية 2030', 'استكشف التطوير الحضري الحديث والمدن المستقبلية في السعودية كجزء من برنامج رؤية 2030 الطموح.', 'اكتشف تحول المدن السعودية، من نيوم إلى الرياض، واستعرض العمارة الحديثة والابتكار الحضري في إطار رؤية 2030.', 'مدن السعودية, رؤية 2030, تطوير حديث, سياحة الشرق الأوسط', now(), now()),
((SELECT id FROM blog_posts WHERE slug = 'saudi-arabia-modern-cities-guide'), 'es', 'Guía de Ciudades Modernas de Arabia Saudí: Desarrollo Visión 2030', 'Explora el desarrollo urbano moderno y las ciudades futuristas de Arabia Saudí como parte del ambicioso programa Visión 2030.', 'Descubre la transformación de las ciudades saudíes, desde NEOM hasta Riad, mostrando arquitectura moderna e innovación urbana bajo Visión 2030.', 'ciudades arabia saudí, visión 2030, desarrollo moderno, turismo medio oriente', now(), now())
ON CONFLICT (post_id, locale) DO NOTHING;