/**
 * North and South American countries data for database seeding
 */

import { CountryData } from "./countries-data";

export const americasCountriesData: CountryData[] = [
  // North America
  {
    code: "CAN",
    continent: "North America",
    region: "Northern America",
    isActive: true,
    translations: [
      { locale: "en", name: "Canada", description: "Canada" },
      { locale: "ar", name: "كندا", description: "كندا" },
      { locale: "es", name: "Canadá", description: "Canadá" },
      { locale: "fr", name: "Canada", description: "Canada" },
      { locale: "pt", name: "Canadá", description: "Canadá" },
      { locale: "ru", name: "Канада", description: "Канада" },
      { locale: "de", name: "Kanada", description: "Kanada" },
      { locale: "it", name: "Canada", description: "Canada" },
    ],
  },
  {
    code: "MEX",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      { locale: "en", name: "Mexico", description: "United Mexican States" },
      {
        locale: "ar",
        name: "المكسيك",
        description: "الولايات المكسيكية المتحدة",
      },
      { locale: "es", name: "México", description: "Estados Unidos Mexicanos" },
      { locale: "fr", name: "Mexique", description: "États-Unis mexicains" },
      { locale: "pt", name: "México", description: "Estados Unidos Mexicanos" },
      {
        locale: "ru",
        name: "Мексика",
        description: "Мексиканские Соединённые Штаты",
      },
      {
        locale: "de",
        name: "Mexiko",
        description: "Vereinigte Mexikanische Staaten",
      },
      { locale: "it", name: "Messico", description: "Stati Uniti Messicani" },
    ],
  },
  {
    code: "USA",
    continent: "North America",
    region: "Northern America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "United States",
        description: "United States of America",
      },
      {
        locale: "ar",
        name: "الولايات المتحدة",
        description: "الولايات المتحدة الأمريكية",
      },
      {
        locale: "es",
        name: "Estados Unidos",
        description: "Estados Unidos de América",
      },
      {
        locale: "fr",
        name: "États-Unis",
        description: "États-Unis d'Amérique",
      },
      {
        locale: "pt",
        name: "Estados Unidos",
        description: "Estados Unidos da América",
      },
      {
        locale: "ru",
        name: "Соединённые Штаты",
        description: "Соединённые Штаты Америки",
      },
      {
        locale: "de",
        name: "Vereinigte Staaten",
        description: "Vereinigte Staaten von Amerika",
      },
      {
        locale: "it",
        name: "Stati Uniti",
        description: "Stati Uniti d'America",
      },
    ],
  },

  // Central America
  {
    code: "BLZ",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      { locale: "en", name: "Belize", description: "Belize" },
      { locale: "ar", name: "بليز", description: "بليز" },
      { locale: "es", name: "Belice", description: "Belice" },
      { locale: "fr", name: "Belize", description: "Belize" },
      { locale: "pt", name: "Belize", description: "Belize" },
      { locale: "ru", name: "Белиз", description: "Белиз" },
      { locale: "de", name: "Belize", description: "Belize" },
      { locale: "it", name: "Belize", description: "Belize" },
    ],
  },
  {
    code: "CRI",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Costa Rica",
        description: "Republic of Costa Rica",
      },
      { locale: "ar", name: "كوستاريكا", description: "جمهورية كوستاريكا" },
      {
        locale: "es",
        name: "Costa Rica",
        description: "República de Costa Rica",
      },
      {
        locale: "fr",
        name: "Costa Rica",
        description: "République du Costa Rica",
      },
      {
        locale: "pt",
        name: "Costa Rica",
        description: "República da Costa Rica",
      },
      {
        locale: "ru",
        name: "Коста-Рика",
        description: "Республика Коста-Рика",
      },
      {
        locale: "de",
        name: "Costa Rica",
        description: "Republik Costa Rica",
      },
      {
        locale: "it",
        name: "Costa Rica",
        description: "Repubblica di Costa Rica",
      },
    ],
  },
  {
    code: "SLV",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "El Salvador",
        description: "Republic of El Salvador",
      },
      { locale: "ar", name: "السلفادور", description: "جمهورية السلفادور" },
      {
        locale: "es",
        name: "El Salvador",
        description: "República de El Salvador",
      },
      { locale: "fr", name: "Salvador", description: "République du Salvador" },
      {
        locale: "pt",
        name: "El Salvador",
        description: "República de El Salvador",
      },
      { locale: "ru", name: "Сальвадор", description: "Республика Сальвадор" },
      {
        locale: "de",
        name: "El Salvador",
        description: "Republik El Salvador",
      },
      {
        locale: "it",
        name: "El Salvador",
        description: "Repubblica di El Salvador",
      },
    ],
  },
  {
    code: "GTM",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      { locale: "en", name: "Guatemala", description: "Republic of Guatemala" },
      { locale: "ar", name: "غواتيمالا", description: "جمهورية غواتيمالا" },
      {
        locale: "es",
        name: "Guatemala",
        description: "República de Guatemala",
      },
      {
        locale: "fr",
        name: "Guatemala",
        description: "République du Guatemala",
      },
      {
        locale: "pt",
        name: "Guatemala",
        description: "República da Guatemala",
      },
      {
        locale: "ru",
        name: "Гватемала",
        description: "Республика Гватемала",
      },
      {
        locale: "de",
        name: "Guatemala",
        description: "Republik Guatemala",
      },
      {
        locale: "it",
        name: "Guatemala",
        description: "Repubblica del Guatemala",
      },
    ],
  },
  {
    code: "HND",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      { locale: "en", name: "Honduras", description: "Republic of Honduras" },
      { locale: "ar", name: "هندوراس", description: "جمهورية هندوراس" },
      { locale: "es", name: "Honduras", description: "República de Honduras" },
      { locale: "fr", name: "Honduras", description: "République du Honduras" },
      { locale: "pt", name: "Honduras", description: "República de Honduras" },
      { locale: "ru", name: "Гондурас", description: "Республика Гондурас" },
      { locale: "de", name: "Honduras", description: "Republik Honduras" },
      {
        locale: "it",
        name: "Honduras",
        description: "Repubblica dell'Honduras",
      },
    ],
  },
  {
    code: "NIC",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      { locale: "en", name: "Nicaragua", description: "Republic of Nicaragua" },
      { locale: "ar", name: "نيكاراغوا", description: "جمهورية نيكاراغوا" },
      {
        locale: "es",
        name: "Nicaragua",
        description: "República de Nicaragua",
      },
      {
        locale: "fr",
        name: "Nicaragua",
        description: "République du Nicaragua",
      },
      {
        locale: "pt",
        name: "Nicarágua",
        description: "República da Nicarágua",
      },
      {
        locale: "ru",
        name: "Никарагуа",
        description: "Республика Никарагуа",
      },
      {
        locale: "de",
        name: "Nicaragua",
        description: "Republik Nicaragua",
      },
      {
        locale: "it",
        name: "Nicaragua",
        description: "Repubblica del Nicaragua",
      },
    ],
  },
  {
    code: "PAN",
    continent: "North America",
    region: "Central America",
    isActive: true,
    translations: [
      { locale: "en", name: "Panama", description: "Republic of Panama" },
      { locale: "ar", name: "بنما", description: "جمهورية بنما" },
      { locale: "es", name: "Panamá", description: "República de Panamá" },
      { locale: "fr", name: "Panama", description: "République du Panama" },
      { locale: "pt", name: "Panamá", description: "República do Panamá" },
      { locale: "ru", name: "Панама", description: "Республика Панама" },
      { locale: "de", name: "Panama", description: "Republik Panama" },
      { locale: "it", name: "Panama", description: "Repubblica di Panama" },
    ],
  },

  // Caribbean
  {
    code: "ATG",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Antigua and Barbuda",
        description: "Antigua and Barbuda",
      },
      {
        locale: "ar",
        name: "أنتيغوا وباربودا",
        description: "أنتيغوا وباربودا",
      },
      {
        locale: "es",
        name: "Antigua y Barbuda",
        description: "Antigua y Barbuda",
      },
      {
        locale: "fr",
        name: "Antigua-et-Barbuda",
        description: "Antigua-et-Barbuda",
      },
      {
        locale: "pt",
        name: "Antígua e Barbuda",
        description: "Antígua e Barbuda",
      },
      {
        locale: "ru",
        name: "Антигуа и Барбуда",
        description: "Антигуа и Барбуда",
      },
      {
        locale: "de",
        name: "Antigua und Barbuda",
        description: "Antigua und Barbuda",
      },
      {
        locale: "it",
        name: "Antigua e Barbuda",
        description: "Antigua e Barbuda",
      },
    ],
  },
  {
    code: "BHS",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Bahamas",
        description: "Commonwealth of the Bahamas",
      },
      { locale: "ar", name: "الباهاما", description: "كومنولث الباهاما" },
      {
        locale: "es",
        name: "Bahamas",
        description: "Commonwealth de las Bahamas",
      },
      {
        locale: "fr",
        name: "Bahamas",
        description: "Commonwealth des Bahamas",
      },
      {
        locale: "pt",
        name: "Bahamas",
        description: "Commonwealth das Bahamas",
      },
      {
        locale: "ru",
        name: "Багамы",
        description: "Содружество Багамских Островов",
      },
      {
        locale: "de",
        name: "Bahamas",
        description: "Commonwealth der Bahamas",
      },
      {
        locale: "it",
        name: "Bahamas",
        description: "Commonwealth delle Bahamas",
      },
    ],
  },
  {
    code: "BRB",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      { locale: "en", name: "Barbados", description: "Barbados" },
      { locale: "ar", name: "بربادوس", description: "بربادوس" },
      { locale: "es", name: "Barbados", description: "Barbados" },
      { locale: "fr", name: "Barbade", description: "Barbade" },
      { locale: "pt", name: "Barbados", description: "Barbados" },
      { locale: "ru", name: "Барбадос", description: "Барбадос" },
      { locale: "de", name: "Barbados", description: "Barbados" },
      { locale: "it", name: "Barbados", description: "Barbados" },
    ],
  },
  {
    code: "CUB",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      { locale: "en", name: "Cuba", description: "Republic of Cuba" },
      { locale: "ar", name: "كوبا", description: "جمهورية كوبا" },
      { locale: "es", name: "Cuba", description: "República de Cuba" },
      { locale: "fr", name: "Cuba", description: "République de Cuba" },
      { locale: "pt", name: "Cuba", description: "República de Cuba" },
      { locale: "ru", name: "Куба", description: "Республика Куба" },
      { locale: "de", name: "Kuba", description: "Republik Kuba" },
      { locale: "it", name: "Cuba", description: "Repubblica di Cuba" },
    ],
  },
  {
    code: "DMA",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Dominica",
        description: "Commonwealth of Dominica",
      },
      { locale: "ar", name: "دومينيكا", description: "كومنولث دومينيكا" },
      {
        locale: "es",
        name: "Dominica",
        description: "Commonwealth de Dominica",
      },
      {
        locale: "fr",
        name: "Dominique",
        description: "Commonwealth de Dominique",
      },
      {
        locale: "pt",
        name: "Dominica",
        description: "Commonwealth de Dominica",
      },
      {
        locale: "ru",
        name: "Доминика",
        description: "Содружество Доминика",
      },
      {
        locale: "de",
        name: "Dominica",
        description: "Commonwealth Dominica",
      },
      {
        locale: "it",
        name: "Dominica",
        description: "Commonwealth di Dominica",
      },
    ],
  },
  {
    code: "DOM",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Dominican Republic",
        description: "Dominican Republic",
      },
      {
        locale: "ar",
        name: "جمهورية الدومينيكان",
        description: "جمهورية الدومينيكان",
      },
      {
        locale: "es",
        name: "República Dominicana",
        description: "República Dominicana",
      },
      {
        locale: "fr",
        name: "République dominicaine",
        description: "République dominicaine",
      },
      {
        locale: "pt",
        name: "República Dominicana",
        description: "República Dominicana",
      },
      {
        locale: "ru",
        name: "Доминиканская Республика",
        description: "Доминиканская Республика",
      },
      {
        locale: "de",
        name: "Dominikanische Republik",
        description: "Dominikanische Republik",
      },
      {
        locale: "it",
        name: "Repubblica Dominicana",
        description: "Repubblica Dominicana",
      },
    ],
  },
  {
    code: "GRD",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      { locale: "en", name: "Grenada", description: "Grenada" },
      { locale: "ar", name: "غرينادا", description: "غرينادا" },
      { locale: "es", name: "Granada", description: "Granada" },
      { locale: "fr", name: "Grenade", description: "Grenade" },
      { locale: "pt", name: "Granada", description: "Granada" },
      { locale: "ru", name: "Гренада", description: "Гренада" },
      { locale: "de", name: "Grenada", description: "Grenada" },
      { locale: "it", name: "Grenada", description: "Grenada" },
    ],
  },
  {
    code: "HTI",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      { locale: "en", name: "Haiti", description: "Republic of Haiti" },
      { locale: "ar", name: "هايتي", description: "جمهورية هايتي" },
      { locale: "es", name: "Haití", description: "República de Haití" },
      { locale: "fr", name: "Haïti", description: "République d'Haïti" },
      { locale: "pt", name: "Haiti", description: "República do Haiti" },
      { locale: "ru", name: "Гаити", description: "Республика Гаити" },
      { locale: "de", name: "Haiti", description: "Republik Haiti" },
      { locale: "it", name: "Haiti", description: "Repubblica di Haiti" },
    ],
  },
  {
    code: "JAM",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      { locale: "en", name: "Jamaica", description: "Jamaica" },
      { locale: "ar", name: "جامايكا", description: "جامايكا" },
      { locale: "es", name: "Jamaica", description: "Jamaica" },
      { locale: "fr", name: "Jamaïque", description: "Jamaïque" },
      { locale: "pt", name: "Jamaica", description: "Jamaica" },
      { locale: "ru", name: "Ямайка", description: "Ямайка" },
      { locale: "de", name: "Jamaika", description: "Jamaika" },
      { locale: "it", name: "Giamaica", description: "Giamaica" },
    ],
  },
  {
    code: "KNA",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Saint Kitts and Nevis",
        description: "Federation of Saint Kitts and Nevis",
      },
      {
        locale: "ar",
        name: "سانت كيتس ونيفيس",
        description: "اتحاد سانت كيتس ونيفيس",
      },
      {
        locale: "es",
        name: "San Cristóbal y Nieves",
        description: "Federación de San Cristóbal y Nieves",
      },
      {
        locale: "fr",
        name: "Saint-Kitts-et-Nevis",
        description: "Fédération de Saint-Kitts-et-Nevis",
      },
      {
        locale: "pt",
        name: "São Cristóvão e Névis",
        description: "Federação de São Cristóvão e Névis",
      },
      {
        locale: "ru",
        name: "Сент-Китс и Невис",
        description: "Федерация Сент-Китс и Невис",
      },
      {
        locale: "de",
        name: "St. Kitts und Nevis",
        description: "Föderation St. Kitts und Nevis",
      },
      {
        locale: "it",
        name: "Saint Kitts e Nevis",
        description: "Federazione di Saint Kitts e Nevis",
      },
    ],
  },
  {
    code: "LCA",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      { locale: "en", name: "Saint Lucia", description: "Saint Lucia" },
      { locale: "ar", name: "سانت لوسيا", description: "سانت لوسيا" },
      { locale: "es", name: "Santa Lucía", description: "Santa Lucía" },
      { locale: "fr", name: "Sainte-Lucie", description: "Sainte-Lucie" },
      { locale: "pt", name: "Santa Lúcia", description: "Santa Lúcia" },
      { locale: "ru", name: "Сент-Люсия", description: "Сент-Люсия" },
      { locale: "de", name: "St. Lucia", description: "St. Lucia" },
      { locale: "it", name: "Santa Lucia", description: "Santa Lucia" },
    ],
  },
  {
    code: "VCT",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Saint Vincent and the Grenadines",
        description: "Saint Vincent and the Grenadines",
      },
      {
        locale: "ar",
        name: "سانت فنسنت والغرينادين",
        description: "سانت فنسنت والغرينادين",
      },
      {
        locale: "es",
        name: "San Vicente y las Granadinas",
        description: "San Vicente y las Granadinas",
      },
      {
        locale: "fr",
        name: "Saint-Vincent-et-les-Grenadines",
        description: "Saint-Vincent-et-les-Grenadines",
      },
      {
        locale: "pt",
        name: "São Vicente e Granadinas",
        description: "São Vicente e Granadinas",
      },
      {
        locale: "ru",
        name: "Сент-Винсент и Гренадины",
        description: "Сент-Винсент и Гренадины",
      },
      {
        locale: "de",
        name: "St. Vincent und die Grenadinen",
        description: "St. Vincent und die Grenadinen",
      },
      {
        locale: "it",
        name: "Saint Vincent e Grenadine",
        description: "Saint Vincent e Grenadine",
      },
    ],
  },
  {
    code: "TTO",
    continent: "North America",
    region: "Caribbean",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Trinidad and Tobago",
        description: "Republic of Trinidad and Tobago",
      },
      {
        locale: "ar",
        name: "ترينيداد وتوباغو",
        description: "جمهورية ترينيداد وتوباغو",
      },
      {
        locale: "es",
        name: "Trinidad y Tobago",
        description: "República de Trinidad y Tobago",
      },
      {
        locale: "fr",
        name: "Trinité-et-Tobago",
        description: "République de Trinité-et-Tobago",
      },
      {
        locale: "pt",
        name: "Trinidad e Tobago",
        description: "República de Trinidad e Tobago",
      },
      {
        locale: "ru",
        name: "Тринидад и Тобаго",
        description: "Республика Тринидад и Тобаго",
      },
      {
        locale: "de",
        name: "Trinidad und Tobago",
        description: "Republik Trinidad und Tobago",
      },
      {
        locale: "it",
        name: "Trinidad e Tobago",
        description: "Repubblica di Trinidad e Tobago",
      },
    ],
  },

  // South America
  {
    code: "ARG",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Argentina", description: "Argentine Republic" },
      { locale: "ar", name: "الأرجنتين", description: "جمهورية الأرجنتين" },
      { locale: "es", name: "Argentina", description: "República Argentina" },
      { locale: "fr", name: "Argentine", description: "République argentine" },
      { locale: "pt", name: "Argentina", description: "República Argentina" },
      {
        locale: "ru",
        name: "Аргентина",
        description: "Аргентинская Республика",
      },
      {
        locale: "de",
        name: "Argentinien",
        description: "Argentinische Republik",
      },
      { locale: "it", name: "Argentina", description: "Repubblica Argentina" },
    ],
  },
  {
    code: "BOL",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Bolivia",
        description: "Plurinational State of Bolivia",
      },
      {
        locale: "ar",
        name: "بوليفيا",
        description: "دولة بوليفيا المتعددة القوميات",
      },
      {
        locale: "es",
        name: "Bolivia",
        description: "Estado Plurinacional de Bolivia",
      },
      {
        locale: "fr",
        name: "Bolivie",
        description: "État plurinational de Bolivie",
      },
      {
        locale: "pt",
        name: "Bolívia",
        description: "Estado Plurinacional da Bolívia",
      },
      {
        locale: "ru",
        name: "Боливия",
        description: "Многонациональное государство Боливия",
      },
      {
        locale: "de",
        name: "Bolivien",
        description: "Plurinationaler Staat Bolivien",
      },
      {
        locale: "it",
        name: "Bolivia",
        description: "Stato Plurinazionale di Bolivia",
      },
    ],
  },
  {
    code: "BRA",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Brazil",
        description: "Federative Republic of Brazil",
      },
      {
        locale: "ar",
        name: "البرازيل",
        description: "جمهورية البرازيل الاتحادية",
      },
      {
        locale: "es",
        name: "Brasil",
        description: "República Federativa del Brasil",
      },
      {
        locale: "fr",
        name: "Brésil",
        description: "République fédérative du Brésil",
      },
      {
        locale: "pt",
        name: "Brasil",
        description: "República Federativa do Brasil",
      },
      {
        locale: "ru",
        name: "Бразилия",
        description: "Федеративная Республика Бразилия",
      },
      {
        locale: "de",
        name: "Brasilien",
        description: "Föderative Republik Brasilien",
      },
      {
        locale: "it",
        name: "Brasile",
        description: "Repubblica Federativa del Brasile",
      },
    ],
  },
  {
    code: "CHL",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Chile", description: "Republic of Chile" },
      { locale: "ar", name: "تشيلي", description: "جمهورية تشيلي" },
      { locale: "es", name: "Chile", description: "República de Chile" },
      { locale: "fr", name: "Chili", description: "République du Chili" },
      { locale: "pt", name: "Chile", description: "República do Chile" },
      { locale: "ru", name: "Чили", description: "Республика Чили" },
      { locale: "de", name: "Chile", description: "Republik Chile" },
      { locale: "it", name: "Cile", description: "Repubblica del Cile" },
    ],
  },
  {
    code: "COL",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Colombia", description: "Republic of Colombia" },
      { locale: "ar", name: "كولومبيا", description: "جمهورية كولومبيا" },
      { locale: "es", name: "Colombia", description: "República de Colombia" },
      { locale: "fr", name: "Colombie", description: "République de Colombie" },
      { locale: "pt", name: "Colômbia", description: "República da Colômbia" },
      { locale: "ru", name: "Колумбия", description: "Республика Колумбия" },
      { locale: "de", name: "Kolumbien", description: "Republik Kolumbien" },
      { locale: "it", name: "Colombia", description: "Repubblica di Colombia" },
    ],
  },
  {
    code: "ECU",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Ecuador", description: "Republic of Ecuador" },
      { locale: "ar", name: "الإكوادور", description: "جمهورية الإكوادور" },
      { locale: "es", name: "Ecuador", description: "República del Ecuador" },
      {
        locale: "fr",
        name: "Équateur",
        description: "République de l'Équateur",
      },
      { locale: "pt", name: "Equador", description: "República do Equador" },
      { locale: "ru", name: "Эквадор", description: "Республика Эквадор" },
      { locale: "de", name: "Ecuador", description: "Republik Ecuador" },
      { locale: "it", name: "Ecuador", description: "Repubblica dell'Ecuador" },
    ],
  },
  {
    code: "GUY",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Guyana",
        description: "Co-operative Republic of Guyana",
      },
      { locale: "ar", name: "غيانا", description: "جمهورية غيانا التعاونية" },
      {
        locale: "es",
        name: "Guyana",
        description: "República Cooperativa de Guyana",
      },
      {
        locale: "fr",
        name: "Guyana",
        description: "République coopérative du Guyana",
      },
      {
        locale: "pt",
        name: "Guiana",
        description: "República Cooperativa da Guiana",
      },
      {
        locale: "ru",
        name: "Гайана",
        description: "Кооперативная Республика Гайана",
      },
      {
        locale: "de",
        name: "Guyana",
        description: "Kooperative Republik Guyana",
      },
      {
        locale: "it",
        name: "Guyana",
        description: "Repubblica Cooperativa della Guyana",
      },
    ],
  },
  {
    code: "PRY",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Paraguay", description: "Republic of Paraguay" },
      { locale: "ar", name: "باراغواي", description: "جمهورية باراغواي" },
      { locale: "es", name: "Paraguay", description: "República del Paraguay" },
      { locale: "fr", name: "Paraguay", description: "République du Paraguay" },
      { locale: "pt", name: "Paraguai", description: "República do Paraguai" },
      { locale: "ru", name: "Парагвай", description: "Республика Парагвай" },
      { locale: "de", name: "Paraguay", description: "Republik Paraguay" },
      {
        locale: "it",
        name: "Paraguay",
        description: "Repubblica del Paraguay",
      },
    ],
  },
  {
    code: "PER",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Peru", description: "Republic of Peru" },
      { locale: "ar", name: "بيرو", description: "جمهورية بيرو" },
      { locale: "es", name: "Perú", description: "República del Perú" },
      { locale: "fr", name: "Pérou", description: "République du Pérou" },
      { locale: "pt", name: "Peru", description: "República do Peru" },
      { locale: "ru", name: "Перу", description: "Республика Перу" },
      { locale: "de", name: "Peru", description: "Republik Peru" },
      { locale: "it", name: "Perù", description: "Repubblica del Perù" },
    ],
  },
  {
    code: "SUR",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      { locale: "en", name: "Suriname", description: "Republic of Suriname" },
      { locale: "ar", name: "سورينام", description: "جمهورية سورينام" },
      { locale: "es", name: "Surinam", description: "República de Surinam" },
      { locale: "fr", name: "Suriname", description: "République du Suriname" },
      { locale: "pt", name: "Suriname", description: "República do Suriname" },
      { locale: "ru", name: "Суринам", description: "Республика Суринам" },
      { locale: "de", name: "Suriname", description: "Republik Suriname" },
      {
        locale: "it",
        name: "Suriname",
        description: "Repubblica del Suriname",
      },
    ],
  },
  {
    code: "URY",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Uruguay",
        description: "Oriental Republic of Uruguay",
      },
      {
        locale: "ar",
        name: "أوروغواي",
        description: "جمهورية أوروغواي الشرقية",
      },
      {
        locale: "es",
        name: "Uruguay",
        description: "República Oriental del Uruguay",
      },
      {
        locale: "fr",
        name: "Uruguay",
        description: "République orientale de l'Uruguay",
      },
      {
        locale: "pt",
        name: "Uruguai",
        description: "República Oriental do Uruguai",
      },
      {
        locale: "ru",
        name: "Уругвай",
        description: "Восточная Республика Уругвай",
      },
      {
        locale: "de",
        name: "Uruguay",
        description: "Republik Östlich des Uruguay",
      },
      {
        locale: "it",
        name: "Uruguay",
        description: "Repubblica Orientale dell'Uruguay",
      },
    ],
  },
  {
    code: "VEN",
    continent: "South America",
    region: "South America",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Venezuela",
        description: "Bolivarian Republic of Venezuela",
      },
      {
        locale: "ar",
        name: "فنزويلا",
        description: "جمهورية فنزويلا البوليفارية",
      },
      {
        locale: "es",
        name: "Venezuela",
        description: "República Bolivariana de Venezuela",
      },
      {
        locale: "fr",
        name: "Venezuela",
        description: "République bolivarienne du Venezuela",
      },
      {
        locale: "pt",
        name: "Venezuela",
        description: "República Bolivariana da Venezuela",
      },
      {
        locale: "ru",
        name: "Венесуэла",
        description: "Боливарианская Республика Венесуэла",
      },
      {
        locale: "de",
        name: "Venezuela",
        description: "Bolivarische Republik Venezuela",
      },
      {
        locale: "it",
        name: "Venezuela",
        description: "Repubblica Bolivariana del Venezuela",
      },
    ],
  },
];
