/**
 * European countries data for database seeding
 */

import { CountryData } from "./countries-data";

export const europeanCountriesData: CountryData[] = [
  {
    code: "ALB",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Albania", description: "Republic of Albania" },
      { locale: "ar", name: "ألبانيا", description: "جمهورية ألبانيا" },
      { locale: "es", name: "Albania", description: "República de Albania" },
      { locale: "fr", name: "Albanie", description: "République d'Albanie" },
    ],
  },
  {
    code: "AND",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Andorra", description: "Principality of Andorra" },
      { locale: "ar", name: "أندورا", description: "إمارة أندورا" },
      { locale: "es", name: "Andorra", description: "Principado de Andorra" },
      { locale: "fr", name: "Andorre", description: "Principauté d'Andorre" },
    ],
  },
  {
    code: "AUT",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Austria", description: "Republic of Austria" },
      { locale: "ar", name: "النمسا", description: "جمهورية النمسا" },
      { locale: "es", name: "Austria", description: "República de Austria" },
      { locale: "fr", name: "Autriche", description: "République d'Autriche" },
    ],
  },
  {
    code: "BLR",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Belarus", description: "Republic of Belarus" },
      { locale: "ar", name: "بيلاروسيا", description: "جمهورية بيلاروسيا" },
      {
        locale: "es",
        name: "Bielorrusia",
        description: "República de Belarús",
      },
      {
        locale: "fr",
        name: "Biélorussie",
        description: "République de Biélorussie",
      },
    ],
  },
  {
    code: "BEL",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Belgium", description: "Kingdom of Belgium" },
      { locale: "ar", name: "بلجيكا", description: "مملكة بلجيكا" },
      { locale: "es", name: "Bélgica", description: "Reino de Bélgica" },
      { locale: "fr", name: "Belgique", description: "Royaume de Belgique" },
    ],
  },
  {
    code: "BIH",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Bosnia and Herzegovina",
        description: "Bosnia and Herzegovina",
      },
      { locale: "ar", name: "البوسنة والهرسك", description: "البوسنة والهرسك" },
      {
        locale: "es",
        name: "Bosnia y Herzegovina",
        description: "Bosnia y Herzegovina",
      },
      {
        locale: "fr",
        name: "Bosnie-Herzégovine",
        description: "Bosnie-Herzégovine",
      },
    ],
  },
  {
    code: "BGR",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Bulgaria", description: "Republic of Bulgaria" },
      { locale: "ar", name: "بلغاريا", description: "جمهورية بلغاريا" },
      { locale: "es", name: "Bulgaria", description: "República de Bulgaria" },
      { locale: "fr", name: "Bulgarie", description: "République de Bulgarie" },
    ],
  },
  {
    code: "HRV",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Croatia", description: "Republic of Croatia" },
      { locale: "ar", name: "كرواتيا", description: "جمهورية كرواتيا" },
      { locale: "es", name: "Croacia", description: "República de Croacia" },
      { locale: "fr", name: "Croatie", description: "République de Croatie" },
    ],
  },
  {
    code: "CYP",
    continent: "Europe",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Cyprus", description: "Republic of Cyprus" },
      { locale: "ar", name: "قبرص", description: "جمهورية قبرص" },
      { locale: "es", name: "Chipre", description: "República de Chipre" },
      { locale: "fr", name: "Chypre", description: "République de Chypre" },
    ],
  },
  {
    code: "CZE",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Czech Republic", description: "Czech Republic" },
      { locale: "ar", name: "التشيك", description: "جمهورية التشيك" },
      { locale: "es", name: "República Checa", description: "República Checa" },
      {
        locale: "fr",
        name: "République tchèque",
        description: "République tchèque",
      },
    ],
  },
  {
    code: "DNK",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Denmark", description: "Kingdom of Denmark" },
      { locale: "ar", name: "الدنمارك", description: "مملكة الدنمارك" },
      { locale: "es", name: "Dinamarca", description: "Reino de Dinamarca" },
      { locale: "fr", name: "Danemark", description: "Royaume du Danemark" },
    ],
  },
  {
    code: "EST",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Estonia", description: "Republic of Estonia" },
      { locale: "ar", name: "إستونيا", description: "جمهورية إستونيا" },
      { locale: "es", name: "Estonia", description: "República de Estonia" },
      { locale: "fr", name: "Estonie", description: "République d'Estonie" },
    ],
  },
  {
    code: "FIN",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Finland", description: "Republic of Finland" },
      { locale: "ar", name: "فنلندا", description: "جمهورية فنلندا" },
      {
        locale: "es",
        name: "Finlandia",
        description: "República de Finlandia",
      },
      { locale: "fr", name: "Finlande", description: "République de Finlande" },
    ],
  },
  {
    code: "FRA",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "France", description: "French Republic" },
      { locale: "ar", name: "فرنسا", description: "الجمهورية الفرنسية" },
      { locale: "es", name: "Francia", description: "República Francesa" },
      { locale: "fr", name: "France", description: "République française" },
    ],
  },
  {
    code: "DEU",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Germany",
        description: "Federal Republic of Germany",
      },
      {
        locale: "ar",
        name: "ألمانيا",
        description: "جمهورية ألمانيا الاتحادية",
      },
      {
        locale: "es",
        name: "Alemania",
        description: "República Federal de Alemania",
      },
      {
        locale: "fr",
        name: "Allemagne",
        description: "République fédérale d'Allemagne",
      },
    ],
  },
  {
    code: "GRC",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Greece", description: "Hellenic Republic" },
      { locale: "ar", name: "اليونان", description: "الجمهورية الهيلينية" },
      { locale: "es", name: "Grecia", description: "República Helénica" },
      { locale: "fr", name: "Grèce", description: "République hellénique" },
    ],
  },
  {
    code: "HUN",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Hungary", description: "Hungary" },
      { locale: "ar", name: "المجر", description: "المجر" },
      { locale: "es", name: "Hungría", description: "Hungría" },
      { locale: "fr", name: "Hongrie", description: "Hongrie" },
    ],
  },
  {
    code: "ISL",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Iceland", description: "Iceland" },
      { locale: "ar", name: "آيسلندا", description: "آيسلندا" },
      { locale: "es", name: "Islandia", description: "Islandia" },
      { locale: "fr", name: "Islande", description: "Islande" },
    ],
  },
  {
    code: "IRL",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Ireland", description: "Ireland" },
      { locale: "ar", name: "أيرلندا", description: "أيرلندا" },
      { locale: "es", name: "Irlanda", description: "Irlanda" },
      { locale: "fr", name: "Irlande", description: "Irlande" },
    ],
  },
  {
    code: "ITA",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Italy", description: "Italian Republic" },
      { locale: "ar", name: "إيطاليا", description: "الجمهورية الإيطالية" },
      { locale: "es", name: "Italia", description: "República Italiana" },
      { locale: "fr", name: "Italie", description: "République italienne" },
    ],
  },
  {
    code: "LVA",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Latvia", description: "Republic of Latvia" },
      { locale: "ar", name: "لاتفيا", description: "جمهورية لاتفيا" },
      { locale: "es", name: "Letonia", description: "República de Letonia" },
      { locale: "fr", name: "Lettonie", description: "République de Lettonie" },
    ],
  },
  {
    code: "LIE",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Liechtenstein",
        description: "Principality of Liechtenstein",
      },
      { locale: "ar", name: "ليختنشتاين", description: "إمارة ليختنشتاين" },
      {
        locale: "es",
        name: "Liechtenstein",
        description: "Principado de Liechtenstein",
      },
      {
        locale: "fr",
        name: "Liechtenstein",
        description: "Principauté du Liechtenstein",
      },
    ],
  },
  {
    code: "LTU",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Lithuania", description: "Republic of Lithuania" },
      { locale: "ar", name: "ليتوانيا", description: "جمهورية ليتوانيا" },
      { locale: "es", name: "Lituania", description: "República de Lituania" },
      { locale: "fr", name: "Lituanie", description: "République de Lituanie" },
    ],
  },
  {
    code: "LUX",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Luxembourg",
        description: "Grand Duchy of Luxembourg",
      },
      {
        locale: "ar",
        name: "لوكسمبورغ",
        description: "دوقية لوكسمبورغ الكبرى",
      },
      {
        locale: "es",
        name: "Luxemburgo",
        description: "Gran Ducado de Luxemburgo",
      },
      {
        locale: "fr",
        name: "Luxembourg",
        description: "Grand-Duché de Luxembourg",
      },
    ],
  },
  {
    code: "MLT",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Malta", description: "Republic of Malta" },
      { locale: "ar", name: "مالطا", description: "جمهورية مالطا" },
      { locale: "es", name: "Malta", description: "República de Malta" },
      { locale: "fr", name: "Malte", description: "République de Malte" },
    ],
  },
  {
    code: "MDA",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Moldova", description: "Republic of Moldova" },
      { locale: "ar", name: "مولدوفا", description: "جمهورية مولدوفا" },
      { locale: "es", name: "Moldavia", description: "República de Moldavia" },
      { locale: "fr", name: "Moldavie", description: "République de Moldavie" },
    ],
  },
  {
    code: "MCO",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Monaco", description: "Principality of Monaco" },
      { locale: "ar", name: "موناكو", description: "إمارة موناكو" },
      { locale: "es", name: "Mónaco", description: "Principado de Mónaco" },
      { locale: "fr", name: "Monaco", description: "Principauté de Monaco" },
    ],
  },
  {
    code: "MNE",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Montenegro", description: "Montenegro" },
      { locale: "ar", name: "الجبل الأسود", description: "الجبل الأسود" },
      { locale: "es", name: "Montenegro", description: "Montenegro" },
      { locale: "fr", name: "Monténégro", description: "Monténégro" },
    ],
  },
  {
    code: "NLD",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Netherlands",
        description: "Kingdom of the Netherlands",
      },
      { locale: "ar", name: "هولندا", description: "مملكة هولندا" },
      {
        locale: "es",
        name: "Países Bajos",
        description: "Reino de los Países Bajos",
      },
      { locale: "fr", name: "Pays-Bas", description: "Royaume des Pays-Bas" },
    ],
  },
  {
    code: "MKD",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "North Macedonia",
        description: "Republic of North Macedonia",
      },
      {
        locale: "ar",
        name: "مقدونيا الشمالية",
        description: "جمهورية مقدونيا الشمالية",
      },
      {
        locale: "es",
        name: "Macedonia del Norte",
        description: "República de Macedonia del Norte",
      },
      {
        locale: "fr",
        name: "Macédoine du Nord",
        description: "République de Macédoine du Nord",
      },
    ],
  },
  {
    code: "NOR",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Norway", description: "Kingdom of Norway" },
      { locale: "ar", name: "النرويج", description: "مملكة النرويج" },
      { locale: "es", name: "Noruega", description: "Reino de Noruega" },
      { locale: "fr", name: "Norvège", description: "Royaume de Norvège" },
    ],
  },
  {
    code: "POL",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Poland", description: "Republic of Poland" },
      { locale: "ar", name: "بولندا", description: "جمهورية بولندا" },
      { locale: "es", name: "Polonia", description: "República de Polonia" },
      { locale: "fr", name: "Pologne", description: "République de Pologne" },
    ],
  },
  {
    code: "PRT",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Portugal", description: "Portuguese Republic" },
      { locale: "ar", name: "البرتغال", description: "الجمهورية البرتغالية" },
      { locale: "es", name: "Portugal", description: "República Portuguesa" },
      { locale: "fr", name: "Portugal", description: "République portugaise" },
    ],
  },
  {
    code: "ROU",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Romania", description: "Romania" },
      { locale: "ar", name: "رومانيا", description: "رومانيا" },
      { locale: "es", name: "Rumania", description: "Rumania" },
      { locale: "fr", name: "Roumanie", description: "Roumanie" },
    ],
  },
  {
    code: "RUS",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Russia", description: "Russian Federation" },
      { locale: "ar", name: "روسيا", description: "الاتحاد الروسي" },
      { locale: "es", name: "Rusia", description: "Federación de Rusia" },
      { locale: "fr", name: "Russie", description: "Fédération de Russie" },
    ],
  },
  {
    code: "SMR",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "San Marino",
        description: "Republic of San Marino",
      },
      { locale: "ar", name: "سان مارينو", description: "جمهورية سان مارينو" },
      {
        locale: "es",
        name: "San Marino",
        description: "República de San Marino",
      },
      {
        locale: "fr",
        name: "Saint-Marin",
        description: "République de Saint-Marin",
      },
    ],
  },
  {
    code: "SRB",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Serbia", description: "Republic of Serbia" },
      { locale: "ar", name: "صربيا", description: "جمهورية صربيا" },
      { locale: "es", name: "Serbia", description: "República de Serbia" },
      { locale: "fr", name: "Serbie", description: "République de Serbie" },
    ],
  },
  {
    code: "SVK",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Slovakia", description: "Slovak Republic" },
      { locale: "ar", name: "سلوفاكيا", description: "جمهورية سلوفاكيا" },
      { locale: "es", name: "Eslovaquia", description: "República Eslovaca" },
      { locale: "fr", name: "Slovaquie", description: "République slovaque" },
    ],
  },
  {
    code: "SVN",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Slovenia", description: "Republic of Slovenia" },
      { locale: "ar", name: "سلوفينيا", description: "جمهورية سلوفينيا" },
      {
        locale: "es",
        name: "Eslovenia",
        description: "República de Eslovenia",
      },
      { locale: "fr", name: "Slovénie", description: "République de Slovénie" },
    ],
  },
  {
    code: "ESP",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Spain", description: "Kingdom of Spain" },
      { locale: "ar", name: "إسبانيا", description: "مملكة إسبانيا" },
      { locale: "es", name: "España", description: "Reino de España" },
      { locale: "fr", name: "Espagne", description: "Royaume d'Espagne" },
    ],
  },
  {
    code: "SWE",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Sweden", description: "Kingdom of Sweden" },
      { locale: "ar", name: "السويد", description: "مملكة السويد" },
      { locale: "es", name: "Suecia", description: "Reino de Suecia" },
      { locale: "fr", name: "Suède", description: "Royaume de Suède" },
    ],
  },
  {
    code: "CHE",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Switzerland", description: "Swiss Confederation" },
      { locale: "ar", name: "سويسرا", description: "الاتحاد السويسري" },
      { locale: "es", name: "Suiza", description: "Confederación Suiza" },
      { locale: "fr", name: "Suisse", description: "Confédération suisse" },
    ],
  },
  {
    code: "UKR",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Ukraine", description: "Ukraine" },
      { locale: "ar", name: "أوكرانيا", description: "أوكرانيا" },
      { locale: "es", name: "Ucrania", description: "Ucrania" },
      { locale: "fr", name: "Ukraine", description: "Ukraine" },
    ],
  },
  {
    code: "GBR",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "United Kingdom",
        description: "United Kingdom of Great Britain and Northern Ireland",
      },
      {
        locale: "ar",
        name: "المملكة المتحدة",
        description: "المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية",
      },
      {
        locale: "es",
        name: "Reino Unido",
        description: "Reino Unido de Gran Bretaña e Irlanda del Norte",
      },
      {
        locale: "fr",
        name: "Royaume-Uni",
        description: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
      },
    ],
  },
  {
    code: "VAT",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Vatican City", description: "Vatican City State" },
      { locale: "ar", name: "الفاتيكان", description: "دولة الفاتيكان" },
      {
        locale: "es",
        name: "Ciudad del Vaticano",
        description: "Estado de la Ciudad del Vaticano",
      },
      {
        locale: "fr",
        name: "Vatican",
        description: "État de la Cité du Vatican",
      },
    ],
  },
];
