/**
 * Asian countries data for database seeding
 */

import { type CountryData } from "./countries-data-africa";

export const asianCountriesData: CountryData[] = [
  {
    code: "AFG",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Afghanistan",
        description: "Islamic Emirate of Afghanistan",
      },
      {
        locale: "ar",
        name: "أفغانستان",
        description: "إمارة أفغانستان الإسلامية",
      },
      {
        locale: "es",
        name: "Afganistán",
        description: "Emirato Islámico de Afganistán",
      },
      {
        locale: "fr",
        name: "Afghanistan",
        description: "Émirat islamique d'Afghanistan",
      },
      {
        locale: "pt",
        name: "Afeganistão",
        description: "Emirado Islâmico do Afeganistão",
      },
      {
        locale: "ru",
        name: "Афганистан",
        description: "Исламский эмират Афганистан",
      },
      {
        locale: "de",
        name: "Afghanistan",
        description: "Islamisches Emirat Afghanistan",
      },
      {
        locale: "it",
        name: "Afghanistan",
        description: "Emirato Islamico dell'Afghanistan",
      },
    ],
  },
  {
    code: "BGD",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Bangladesh",
        description: "People's Republic of Bangladesh",
      },
      {
        locale: "ar",
        name: "بنغلاديش",
        description: "جمهورية بنغلاديش الشعبية",
      },
      {
        locale: "es",
        name: "Bangladesh",
        description: "República Popular de Bangladesh",
      },
      {
        locale: "fr",
        name: "Bangladesh",
        description: "République populaire du Bangladesh",
      },
      {
        locale: "pt",
        name: "Bangladesh",
        description: "República Popular do Bangladesh",
      },
      {
        locale: "ru",
        name: "Бангладеш",
        description: "Народная Республика Бангладеш",
      },
      {
        locale: "de",
        name: "Bangladesch",
        description: "Volksrepublik Bangladesch",
      },
      {
        locale: "it",
        name: "Bangladesh",
        description: "Repubblica Popolare del Bangladesh",
      },
    ],
  },
  {
    code: "BTN",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Bhutan", description: "Kingdom of Bhutan" },
      { locale: "ar", name: "بوتان", description: "مملكة بوتان" },
      { locale: "es", name: "Bután", description: "Reino de Bután" },
      { locale: "fr", name: "Bhoutan", description: "Royaume du Bhoutan" },
      { locale: "pt", name: "Butão", description: "Reino do Butão" },
      { locale: "ru", name: "Бутан", description: "Королевство Бутан" },
      { locale: "de", name: "Bhutan", description: "Königreich Bhutan" },
      { locale: "it", name: "Bhutan", description: "Regno del Bhutan" },
    ],
  },
  {
    code: "BRN",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Brunei", description: "Brunei Darussalam" },
      { locale: "ar", name: "بروناي", description: "بروناي دار السلام" },
      { locale: "es", name: "Brunéi", description: "Brunéi Darussalam" },
      { locale: "fr", name: "Brunéi", description: "Brunéi Darussalam" },
      { locale: "pt", name: "Brunei", description: "Brunei Darussalam" },
      { locale: "ru", name: "Бруней", description: "Бруней-Даруссалам" },
      { locale: "de", name: "Brunei", description: "Brunei Darussalam" },
      { locale: "it", name: "Brunei", description: "Brunei Darussalam" },
    ],
  },
  {
    code: "KHM",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Cambodia", description: "Kingdom of Cambodia" },
      { locale: "ar", name: "كمبوديا", description: "مملكة كمبوديا" },
      { locale: "es", name: "Camboya", description: "Reino de Camboya" },
      { locale: "fr", name: "Cambodge", description: "Royaume du Cambodge" },
      { locale: "pt", name: "Camboja", description: "Reino do Camboja" },
      { locale: "ru", name: "Камбоджа", description: "Королевство Камбоджа" },
      {
        locale: "de",
        name: "Kambodscha",
        description: "Königreich Kambodscha",
      },
      { locale: "it", name: "Cambogia", description: "Regno di Cambogia" },
    ],
  },
  {
    code: "CHN",
    continent: "Asia",
    region: "Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "China",
        description: "People's Republic of China",
      },
      { locale: "ar", name: "الصين", description: "جمهورية الصين الشعبية" },
      { locale: "es", name: "China", description: "República Popular China" },
      {
        locale: "fr",
        name: "Chine",
        description: "République populaire de Chine",
      },
      {
        locale: "pt",
        name: "China",
        description: "República Popular da China",
      },
      {
        locale: "ru",
        name: "Китай",
        description: "Китайская Народная Республика",
      },
      {
        locale: "de",
        name: "China",
        description: "Volksrepublik China",
      },
      {
        locale: "it",
        name: "Cina",
        description: "Repubblica Popolare Cinese",
      },
    ],
  },
  {
    code: "TLS",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "East Timor",
        description: "Democratic Republic of Timor-Leste",
      },
      {
        locale: "ar",
        name: "تيمور الشرقية",
        description: "جمهورية تيمور الشرقية الديمقراطية",
      },
      {
        locale: "es",
        name: "Timor Oriental",
        description: "República Democrática de Timor Oriental",
      },
      {
        locale: "fr",
        name: "Timor oriental",
        description: "République démocratique du Timor oriental",
      },
      {
        locale: "pt",
        name: "Timor-Leste",
        description: "República Democrática de Timor-Leste",
      },
      {
        locale: "ru",
        name: "Восточный Тимор",
        description: "Демократическая Республика Тимор-Лешти",
      },
      {
        locale: "de",
        name: "Osttimor",
        description: "Demokratische Republik Timor-Leste",
      },
      {
        locale: "it",
        name: "Timor Est",
        description: "Repubblica Democratica di Timor Est",
      },
    ],
  },
  {
    code: "GEO",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Georgia", description: "Georgia" },
      { locale: "ar", name: "جورجيا", description: "جورجيا" },
      { locale: "es", name: "Georgia", description: "Georgia" },
      { locale: "fr", name: "Géorgie", description: "Géorgie" },
      { locale: "pt", name: "Geórgia", description: "Geórgia" },
      { locale: "ru", name: "Грузия", description: "Грузия" },
      { locale: "de", name: "Georgien", description: "Georgien" },
      { locale: "it", name: "Georgia", description: "Georgia" },
    ],
  },
  {
    code: "IND",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "India", description: "Republic of India" },
      { locale: "ar", name: "الهند", description: "جمهورية الهند" },
      { locale: "es", name: "India", description: "República de la India" },
      { locale: "fr", name: "Inde", description: "République de l'Inde" },
      { locale: "pt", name: "Índia", description: "República da Índia" },
      { locale: "ru", name: "Индия", description: "Республика Индия" },
      { locale: "de", name: "Indien", description: "Republik Indien" },
      { locale: "it", name: "India", description: "Repubblica dell'India" },
    ],
  },
  {
    code: "IDN",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Indonesia", description: "Republic of Indonesia" },
      { locale: "ar", name: "إندونيسيا", description: "جمهورية إندونيسيا" },
      {
        locale: "es",
        name: "Indonesia",
        description: "República de Indonesia",
      },
      {
        locale: "fr",
        name: "Indonésie",
        description: "République d'Indonésie",
      },
      {
        locale: "pt",
        name: "Indonésia",
        description: "República da Indonésia",
      },
      {
        locale: "ru",
        name: "Индонезия",
        description: "Республика Индонезия",
      },
      {
        locale: "de",
        name: "Indonesien",
        description: "Republik Indonesien",
      },
      {
        locale: "it",
        name: "Indonesia",
        description: "Repubblica di Indonesia",
      },
    ],
  },
  {
    code: "IRN",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Iran", description: "Islamic Republic of Iran" },
      { locale: "ar", name: "إيران", description: "جمهورية إيران الإسلامية" },
      { locale: "es", name: "Irán", description: "República Islámica de Irán" },
      {
        locale: "fr",
        name: "Iran",
        description: "République islamique d'Iran",
      },
      {
        locale: "pt",
        name: "Irã",
        description: "República Islâmica do Irã",
      },
      {
        locale: "ru",
        name: "Иран",
        description: "Исламская Республика Иран",
      },
      {
        locale: "de",
        name: "Iran",
        description: "Islamische Republik Iran",
      },
      {
        locale: "it",
        name: "Iran",
        description: "Repubblica Islamica dell'Iran",
      },
    ],
  },
  {
    code: "IRQ",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Iraq", description: "Republic of Iraq" },
      { locale: "ar", name: "العراق", description: "جمهورية العراق" },
      { locale: "es", name: "Irak", description: "República de Irak" },
      { locale: "fr", name: "Irak", description: "République d'Irak" },
      { locale: "pt", name: "Iraque", description: "República do Iraque" },
      { locale: "ru", name: "Ирак", description: "Республика Ирак" },
      { locale: "de", name: "Irak", description: "Republik Irak" },
      { locale: "it", name: "Iraq", description: "Repubblica dell'Iraq" },
    ],
  },
  {
    code: "ISR",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Israel", description: "State of Israel" },
      { locale: "ar", name: "إسرائيل", description: "دولة إسرائيل" },
      { locale: "es", name: "Israel", description: "Estado de Israel" },
      { locale: "fr", name: "Israël", description: "État d'Israël" },
      { locale: "pt", name: "Israel", description: "Estado de Israel" },
      { locale: "ru", name: "Израиль", description: "Государство Израиль" },
      { locale: "de", name: "Israel", description: "Staat Israel" },
      { locale: "it", name: "Israele", description: "Stato di Israele" },
    ],
  },
  {
    code: "JPN",
    continent: "Asia",
    region: "Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Japan", description: "Japan" },
      { locale: "ar", name: "اليابان", description: "اليابان" },
      { locale: "es", name: "Japón", description: "Japón" },
      { locale: "fr", name: "Japon", description: "Japon" },
      { locale: "pt", name: "Japão", description: "Japão" },
      { locale: "ru", name: "Япония", description: "Япония" },
      { locale: "de", name: "Japan", description: "Japan" },
      { locale: "it", name: "Giappone", description: "Giappone" },
    ],
  },
  {
    code: "JOR",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Jordan",
        description: "Hashemite Kingdom of Jordan",
      },
      {
        locale: "ar",
        name: "الأردن",
        description: "المملكة الأردنية الهاشمية",
      },
      {
        locale: "es",
        name: "Jordania",
        description: "Reino Hachemita de Jordania",
      },
      {
        locale: "fr",
        name: "Jordanie",
        description: "Royaume hachémite de Jordanie",
      },
      {
        locale: "pt",
        name: "Jordânia",
        description: "Reino Hachemita da Jordânia",
      },
      {
        locale: "ru",
        name: "Иордания",
        description: "Иорданское Хашимитское Королевство",
      },
      {
        locale: "de",
        name: "Jordanien",
        description: "Haschemitisches Königreich Jordanien",
      },
      {
        locale: "it",
        name: "Giordania",
        description: "Regno Hascemita di Giordania",
      },
    ],
  },
  {
    code: "KAZ",
    continent: "Asia",
    region: "Central Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Kazakhstan",
        description: "Republic of Kazakhstan",
      },
      { locale: "ar", name: "كازاخستان", description: "جمهورية كازاخستان" },
      {
        locale: "es",
        name: "Kazajistán",
        description: "República de Kazajistán",
      },
      {
        locale: "fr",
        name: "Kazakhstan",
        description: "République du Kazakhstan",
      },
      {
        locale: "pt",
        name: "Cazaquistão",
        description: "República do Cazaquistão",
      },
      {
        locale: "ru",
        name: "Казахстан",
        description: "Республика Казахстан",
      },
      {
        locale: "de",
        name: "Kasachstan",
        description: "Republik Kasachstan",
      },
      {
        locale: "it",
        name: "Kazakistan",
        description: "Repubblica del Kazakistan",
      },
    ],
  },
  {
    code: "KWT",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Kuwait", description: "State of Kuwait" },
      { locale: "ar", name: "الكويت", description: "دولة الكويت" },
      { locale: "es", name: "Kuwait", description: "Estado de Kuwait" },
      { locale: "fr", name: "Koweït", description: "État du Koweït" },
      { locale: "pt", name: "Kuwait", description: "Estado do Kuwait" },
      { locale: "ru", name: "Кувейт", description: "Государство Кувейт" },
      { locale: "de", name: "Kuwait", description: "Staat Kuwait" },
      { locale: "it", name: "Kuwait", description: "Stato del Kuwait" },
    ],
  },
  {
    code: "KGZ",
    continent: "Asia",
    region: "Central Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Kyrgyzstan", description: "Kyrgyz Republic" },
      { locale: "ar", name: "قيرغيزستان", description: "جمهورية قيرغيزستان" },
      { locale: "es", name: "Kirguistán", description: "República Kirguisa" },
      {
        locale: "fr",
        name: "Kirghizistan",
        description: "République kirghize",
      },
      {
        locale: "pt",
        name: "Quirguistão",
        description: "República Quirguiz",
      },
      {
        locale: "ru",
        name: "Кыргызстан",
        description: "Кыргызская Республика",
      },
      {
        locale: "de",
        name: "Kirgisistan",
        description: "Kirgisische Republik",
      },
      {
        locale: "it",
        name: "Kirghizistan",
        description: "Repubblica del Kirghizistan",
      },
    ],
  },
  {
    code: "LAO",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Laos",
        description: "Lao People's Democratic Republic",
      },
      {
        locale: "ar",
        name: "لاوس",
        description: "جمهورية لاوس الديمقراطية الشعبية",
      },
      {
        locale: "es",
        name: "Laos",
        description: "República Democrática Popular Lao",
      },
      {
        locale: "fr",
        name: "Laos",
        description: "République démocratique populaire lao",
      },
      {
        locale: "pt",
        name: "Laos",
        description: "República Democrática Popular do Laos",
      },
      {
        locale: "ru",
        name: "Лаос",
        description: "Лаосская Народно-Демократическая Республика",
      },
      {
        locale: "de",
        name: "Laos",
        description: "Demokratische Volksrepublik Laos",
      },
      {
        locale: "it",
        name: "Laos",
        description: "Repubblica Democratica Popolare del Laos",
      },
    ],
  },
  {
    code: "LBN",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Lebanon", description: "Lebanese Republic" },
      { locale: "ar", name: "لبنان", description: "الجمهورية اللبنانية" },
      { locale: "es", name: "Líbano", description: "República Libanesa" },
      { locale: "fr", name: "Liban", description: "République libanaise" },
      { locale: "pt", name: "Líbano", description: "República Libanesa" },
      { locale: "ru", name: "Ливан", description: "Ливанская Республика" },
      { locale: "de", name: "Libanon", description: "Libanesische Republik" },
      { locale: "it", name: "Libano", description: "Repubblica Libanese" },
    ],
  },
  {
    code: "MYS",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Malaysia", description: "Malaysia" },
      { locale: "ar", name: "ماليزيا", description: "ماليزيا" },
      { locale: "es", name: "Malasia", description: "Malasia" },
      { locale: "fr", name: "Malaisie", description: "Malaisie" },
      { locale: "pt", name: "Malásia", description: "Malásia" },
      { locale: "ru", name: "Малайзия", description: "Малайзия" },
      { locale: "de", name: "Malaysia", description: "Malaysia" },
      { locale: "it", name: "Malesia", description: "Malesia" },
    ],
  },
  {
    code: "MDV",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Maldives", description: "Republic of Maldives" },
      {
        locale: "ar",
        name: "جزر المالديف",
        description: "جمهورية جزر المالديف",
      },
      {
        locale: "es",
        name: "Maldivas",
        description: "República de las Maldivas",
      },
      {
        locale: "fr",
        name: "Maldives",
        description: "République des Maldives",
      },
      {
        locale: "pt",
        name: "Maldivas",
        description: "República das Maldivas",
      },
      {
        locale: "ru",
        name: "Мальдивы",
        description: "Республика Мальдивы",
      },
      {
        locale: "de",
        name: "Malediven",
        description: "Republik Malediven",
      },
      {
        locale: "it",
        name: "Maldive",
        description: "Repubblica delle Maldive",
      },
    ],
  },
  {
    code: "MNG",
    continent: "Asia",
    region: "Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Mongolia", description: "Mongolia" },
      { locale: "ar", name: "منغوليا", description: "منغوليا" },
      { locale: "es", name: "Mongolia", description: "Mongolia" },
      { locale: "fr", name: "Mongolie", description: "Mongolie" },
      { locale: "pt", name: "Mongólia", description: "Mongólia" },
      { locale: "ru", name: "Монголия", description: "Монголия" },
      { locale: "de", name: "Mongolei", description: "Mongolei" },
      { locale: "it", name: "Mongolia", description: "Mongolia" },
    ],
  },
  {
    code: "MMR",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Myanmar",
        description: "Republic of the Union of Myanmar",
      },
      { locale: "ar", name: "ميانمار", description: "جمهورية اتحاد ميانمار" },
      {
        locale: "es",
        name: "Myanmar",
        description: "República de la Unión de Myanmar",
      },
      {
        locale: "fr",
        name: "Myanmar",
        description: "République de l'Union du Myanmar",
      },
      {
        locale: "pt",
        name: "Myanmar",
        description: "República da União de Myanmar",
      },
      {
        locale: "ru",
        name: "Мьянма",
        description: "Республика Союз Мьянма",
      },
      {
        locale: "de",
        name: "Myanmar",
        description: "Republik der Union Myanmar",
      },
      {
        locale: "it",
        name: "Myanmar",
        description: "Repubblica dell'Unione del Myanmar",
      },
    ],
  },
  {
    code: "NPL",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Nepal",
        description: "Federal Democratic Republic of Nepal",
      },
      {
        locale: "ar",
        name: "نيبال",
        description: "جمهورية نيبال الديمقراطية الاتحادية",
      },
      {
        locale: "es",
        name: "Nepal",
        description: "República Federal Democrática de Nepal",
      },
      {
        locale: "fr",
        name: "Népal",
        description: "République fédérale démocratique du Népal",
      },
      {
        locale: "pt",
        name: "Nepal",
        description: "República Federal Democrática do Nepal",
      },
      {
        locale: "ru",
        name: "Непал",
        description: "Федеративная Демократическая Республика Непал",
      },
      {
        locale: "de",
        name: "Nepal",
        description: "Demokratische Bundesrepublik Nepal",
      },
      {
        locale: "it",
        name: "Nepal",
        description: "Repubblica Federale Democratica del Nepal",
      },
    ],
  },
  {
    code: "PRK",
    continent: "Asia",
    region: "Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "North Korea",
        description: "Democratic People's Republic of Korea",
      },
      {
        locale: "ar",
        name: "كوريا الشمالية",
        description: "جمهورية كوريا الديمقراطية الشعبية",
      },
      {
        locale: "es",
        name: "Corea del Norte",
        description: "República Popular Democrática de Corea",
      },
      {
        locale: "fr",
        name: "Corée du Nord",
        description: "République populaire démocratique de Corée",
      },
      {
        locale: "pt",
        name: "Coreia do Norte",
        description: "República Popular Democrática da Coreia",
      },
      {
        locale: "ru",
        name: "Северная Корея",
        description: "Корейская Народно-Демократическая Республика",
      },
      {
        locale: "de",
        name: "Nordkorea",
        description: "Demokratische Volksrepublik Korea",
      },
      {
        locale: "it",
        name: "Corea del Nord",
        description: "Repubblica Popolare Democratica di Corea",
      },
    ],
  },
  {
    code: "OMN",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Oman", description: "Sultanate of Oman" },
      { locale: "ar", name: "عُمان", description: "سلطنة عُمان" },
      { locale: "es", name: "Omán", description: "Sultanato de Omán" },
      { locale: "fr", name: "Oman", description: "Sultanat d'Oman" },
      { locale: "pt", name: "Omã", description: "Sultanato de Omã" },
      { locale: "ru", name: "Оман", description: "Султанат Оман" },
      { locale: "de", name: "Oman", description: "Sultanat Oman" },
      { locale: "it", name: "Oman", description: "Sultanato dell'Oman" },
    ],
  },
  {
    code: "PAK",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Pakistan",
        description: "Islamic Republic of Pakistan",
      },
      {
        locale: "ar",
        name: "باكستان",
        description: "جمهورية باكستان الإسلامية",
      },
      {
        locale: "es",
        name: "Pakistán",
        description: "República Islámica de Pakistán",
      },
      {
        locale: "fr",
        name: "Pakistan",
        description: "République islamique du Pakistan",
      },
      {
        locale: "pt",
        name: "Paquistão",
        description: "República Islâmica do Paquistão",
      },
      {
        locale: "ru",
        name: "Пакистан",
        description: "Исламская Республика Пакистан",
      },
      {
        locale: "de",
        name: "Pakistan",
        description: "Islamische Republik Pakistan",
      },
      {
        locale: "it",
        name: "Pakistan",
        description: "Repubblica Islamica del Pakistan",
      },
    ],
  },
  {
    code: "PSE",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Palestine", description: "State of Palestine" },
      { locale: "ar", name: "فلسطين", description: "دولة فلسطين" },
      { locale: "es", name: "Palestina", description: "Estado de Palestina" },
      { locale: "fr", name: "Palestine", description: "État de Palestine" },
      { locale: "pt", name: "Palestina", description: "Estado da Palestina" },
      { locale: "ru", name: "Палестина", description: "Государство Палестина" },
      { locale: "de", name: "Palästina", description: "Staat Palästina" },
      { locale: "it", name: "Palestina", description: "Stato di Palestina" },
    ],
  },
  {
    code: "PHL",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Philippines",
        description: "Republic of the Philippines",
      },
      { locale: "ar", name: "الفلبين", description: "جمهورية الفلبين" },
      {
        locale: "es",
        name: "Filipinas",
        description: "República de Filipinas",
      },
      {
        locale: "fr",
        name: "Philippines",
        description: "République des Philippines",
      },
      {
        locale: "pt",
        name: "Filipinas",
        description: "República das Filipinas",
      },
      {
        locale: "ru",
        name: "Филиппины",
        description: "Республика Филиппины",
      },
      {
        locale: "de",
        name: "Philippinen",
        description: "Republik der Philippinen",
      },
      {
        locale: "it",
        name: "Filippine",
        description: "Repubblica delle Filippine",
      },
    ],
  },
  {
    code: "QAT",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Qatar", description: "State of Qatar" },
      { locale: "ar", name: "قطر", description: "دولة قطر" },
      { locale: "es", name: "Catar", description: "Estado de Catar" },
      { locale: "fr", name: "Qatar", description: "État du Qatar" },
      { locale: "pt", name: "Catar", description: "Estado do Catar" },
      { locale: "ru", name: "Катар", description: "Государство Катар" },
      { locale: "de", name: "Katar", description: "Staat Katar" },
      { locale: "it", name: "Qatar", description: "Stato del Qatar" },
    ],
  },
  {
    code: "SAU",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Saudi Arabia",
        description: "Kingdom of Saudi Arabia",
      },
      {
        locale: "ar",
        name: "السعودية",
        description: "المملكة العربية السعودية",
      },
      {
        locale: "es",
        name: "Arabia Saudí",
        description: "Reino de Arabia Saudí",
      },
      {
        locale: "fr",
        name: "Arabie saoudite",
        description: "Royaume d'Arabie saoudite",
      },
      {
        locale: "pt",
        name: "Arábia Saudita",
        description: "Reino da Arábia Saudita",
      },
      {
        locale: "ru",
        name: "Саудовская Аравия",
        description: "Королевство Саудовская Аравия",
      },
      {
        locale: "de",
        name: "Saudi-Arabien",
        description: "Königreich Saudi-Arabien",
      },
      {
        locale: "it",
        name: "Arabia Saudita",
        description: "Regno dell'Arabia Saudita",
      },
    ],
  },
  {
    code: "SGP",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Singapore", description: "Republic of Singapore" },
      { locale: "ar", name: "سنغافورة", description: "جمهورية سنغافورة" },
      { locale: "es", name: "Singapur", description: "República de Singapur" },
      {
        locale: "fr",
        name: "Singapour",
        description: "République de Singapour",
      },
      {
        locale: "pt",
        name: "Singapura",
        description: "República de Singapura",
      },
      {
        locale: "ru",
        name: "Сингапур",
        description: "Республика Сингапур",
      },
      {
        locale: "de",
        name: "Singapur",
        description: "Republik Singapur",
      },
      {
        locale: "it",
        name: "Singapore",
        description: "Repubblica di Singapore",
      },
    ],
  },
  {
    code: "KOR",
    continent: "Asia",
    region: "Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "South Korea", description: "Republic of Korea" },
      { locale: "ar", name: "كوريا الجنوبية", description: "جمهورية كوريا" },
      {
        locale: "es",
        name: "Corea del Sur",
        description: "República de Corea",
      },
      {
        locale: "fr",
        name: "Corée du Sud",
        description: "République de Corée",
      },
      {
        locale: "pt",
        name: "Coreia do Sul",
        description: "República da Coreia",
      },
      {
        locale: "ru",
        name: "Южная Корея",
        description: "Республика Корея",
      },
      {
        locale: "de",
        name: "Südkorea",
        description: "Republik Korea",
      },
      {
        locale: "it",
        name: "Corea del Sud",
        description: "Repubblica di Corea",
      },
    ],
  },
  {
    code: "LKA",
    continent: "Asia",
    region: "Southern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Sri Lanka",
        description: "Democratic Socialist Republic of Sri Lanka",
      },
      {
        locale: "ar",
        name: "سريلانكا",
        description: "جمهورية سريلانكا الديمقراطية الاشتراكية",
      },
      {
        locale: "es",
        name: "Sri Lanka",
        description: "República Democrática Socialista de Sri Lanka",
      },
      {
        locale: "fr",
        name: "Sri Lanka",
        description: "République démocratique socialiste du Sri Lanka",
      },
      {
        locale: "pt",
        name: "Sri Lanka",
        description: "República Democrática Socialista do Sri Lanka",
      },
      {
        locale: "ru",
        name: "Шри-Ланка",
        description: "Демократическая Социалистическая Республика Шри-Ланка",
      },
      {
        locale: "de",
        name: "Sri Lanka",
        description: "Demokratische Sozialistische Republik Sri Lanka",
      },
      {
        locale: "it",
        name: "Sri Lanka",
        description: "Repubblica Democratica Socialista dello Sri Lanka",
      },
    ],
  },
  {
    code: "SYR",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Syria", description: "Syrian Arab Republic" },
      { locale: "ar", name: "سوريا", description: "الجمهورية العربية السورية" },
      { locale: "es", name: "Siria", description: "República Árabe Siria" },
      { locale: "fr", name: "Syrie", description: "République arabe syrienne" },
      { locale: "pt", name: "Síria", description: "República Árabe Síria" },
      {
        locale: "ru",
        name: "Сирия",
        description: "Сирийская Арабская Республика",
      },
      {
        locale: "de",
        name: "Syrien",
        description: "Arabische Republik Syrien",
      },
      { locale: "it", name: "Siria", description: "Repubblica Araba Siriana" },
    ],
  },
  {
    code: "TJK",
    continent: "Asia",
    region: "Central Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Tajikistan",
        description: "Republic of Tajikistan",
      },
      { locale: "ar", name: "طاجيكستان", description: "جمهورية طاجيكستان" },
      {
        locale: "es",
        name: "Tayikistán",
        description: "República de Tayikistán",
      },
      {
        locale: "fr",
        name: "Tadjikistan",
        description: "République du Tadjikistan",
      },
      {
        locale: "pt",
        name: "Tajiquistão",
        description: "República do Tajiquistão",
      },
      {
        locale: "ru",
        name: "Таджикистан",
        description: "Республика Таджикистан",
      },
      {
        locale: "de",
        name: "Tadschikistan",
        description: "Republik Tadschikistan",
      },
      {
        locale: "it",
        name: "Tagikistan",
        description: "Repubblica del Tagikistan",
      },
    ],
  },
  {
    code: "THA",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Thailand", description: "Kingdom of Thailand" },
      { locale: "ar", name: "تايلاند", description: "مملكة تايلاند" },
      { locale: "es", name: "Tailandia", description: "Reino de Tailandia" },
      { locale: "fr", name: "Thaïlande", description: "Royaume de Thaïlande" },
      { locale: "pt", name: "Tailândia", description: "Reino da Tailândia" },
      { locale: "ru", name: "Таиланд", description: "Королевство Таиланд" },
      { locale: "de", name: "Thailand", description: "Königreich Thailand" },
      { locale: "it", name: "Tailandia", description: "Regno di Tailandia" },
    ],
  },
  {
    code: "TUR",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Turkey", description: "Republic of Turkey" },
      { locale: "ar", name: "تركيا", description: "جمهورية تركيا" },
      { locale: "es", name: "Turquía", description: "República de Turquía" },
      { locale: "fr", name: "Turquie", description: "République de Turquie" },
      { locale: "pt", name: "Turquia", description: "República da Turquia" },
      { locale: "ru", name: "Турция", description: "Республика Турция" },
      { locale: "de", name: "Türkei", description: "Republik Türkei" },
      { locale: "it", name: "Turchia", description: "Repubblica di Turchia" },
    ],
  },
  {
    code: "TKM",
    continent: "Asia",
    region: "Central Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Turkmenistan", description: "Turkmenistan" },
      { locale: "ar", name: "تركمانستان", description: "تركمانستان" },
      { locale: "es", name: "Turkmenistán", description: "Turkmenistán" },
      { locale: "fr", name: "Turkménistan", description: "Turkménistan" },
      { locale: "pt", name: "Turcomenistão", description: "Turcomenistão" },
      { locale: "ru", name: "Туркменистан", description: "Туркменистан" },
      { locale: "de", name: "Turkmenistan", description: "Turkmenistan" },
      { locale: "it", name: "Turkmenistan", description: "Turkmenistan" },
    ],
  },
  {
    code: "ARE",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "United Arab Emirates",
        description: "United Arab Emirates",
      },
      {
        locale: "ar",
        name: "الإمارات العربية المتحدة",
        description: "دولة الإمارات العربية المتحدة",
      },
      {
        locale: "es",
        name: "Emiratos Árabes Unidos",
        description: "Emiratos Árabes Unidos",
      },
      {
        locale: "fr",
        name: "Émirats arabes unis",
        description: "Émirats arabes unis",
      },
      {
        locale: "pt",
        name: "Emirados Árabes Unidos",
        description: "Emirados Árabes Unidos",
      },
      {
        locale: "ru",
        name: "Объединенные Арабские Эмираты",
        description: "Объединенные Арабские Эмираты",
      },
      {
        locale: "de",
        name: "Vereinigte Arabische Emirate",
        description: "Vereinigte Arabische Emirate",
      },
      {
        locale: "it",
        name: "Emirati Arabi Uniti",
        description: "Emirati Arabi Uniti",
      },
    ],
  },
  {
    code: "UZB",
    continent: "Asia",
    region: "Central Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Uzbekistan",
        description: "Republic of Uzbekistan",
      },
      { locale: "ar", name: "أوزبكستان", description: "جمهورية أوزبكستان" },
      {
        locale: "es",
        name: "Uzbekistán",
        description: "República de Uzbekistán",
      },
      {
        locale: "fr",
        name: "Ouzbékistan",
        description: "République d'Ouzbékistan",
      },
      {
        locale: "pt",
        name: "Uzbequistão",
        description: "República do Uzbequistão",
      },
      {
        locale: "ru",
        name: "Узбекистан",
        description: "Республика Узбекистан",
      },
      {
        locale: "de",
        name: "Usbekistan",
        description: "Republik Usbekistan",
      },
      {
        locale: "it",
        name: "Uzbekistan",
        description: "Repubblica dell'Uzbekistan",
      },
    ],
  },
  {
    code: "VNM",
    continent: "Asia",
    region: "South-Eastern Asia",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Vietnam",
        description: "Socialist Republic of Vietnam",
      },
      {
        locale: "ar",
        name: "فيتنام",
        description: "جمهورية فيتنام الاشتراكية",
      },
      {
        locale: "es",
        name: "Vietnam",
        description: "República Socialista de Vietnam",
      },
      {
        locale: "fr",
        name: "Vietnam",
        description: "République socialiste du Vietnam",
      },
      {
        locale: "pt",
        name: "Vietnã",
        description: "República Socialista do Vietnã",
      },
      {
        locale: "ru",
        name: "Вьетнам",
        description: "Социалистическая Республика Вьетнам",
      },
      {
        locale: "de",
        name: "Vietnam",
        description: "Sozialistische Republik Vietnam",
      },
      {
        locale: "it",
        name: "Vietnam",
        description: "Repubblica Socialista del Vietnam",
      },
    ],
  },
  {
    code: "YEM",
    continent: "Asia",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Yemen", description: "Republic of Yemen" },
      { locale: "ar", name: "اليمن", description: "جمهورية اليمن" },
      { locale: "es", name: "Yemen", description: "República de Yemen" },
      { locale: "fr", name: "Yémen", description: "République du Yémen" },
      { locale: "pt", name: "Iêmen", description: "República do Iêmen" },
      { locale: "ru", name: "Йемен", description: "Республика Йемен" },
      { locale: "de", name: "Jemen", description: "Republik Jemen" },
      { locale: "it", name: "Yemen", description: "Repubblica dello Yemen" },
    ],
  },
];
