/**
 * European countries data for database seeding
 */

import { type CountryData } from "./countries-data-africa";

export const europeanCountriesData: CountryData[] = [
  {
    code: "ALB",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Albania", description: "Republic of Albania" },
      { locale: "ar", name: "ألبانيا", description: "جمهورية ألبانيا" },
      { locale: "es", name: "Albania", description: "República de Albania" },
      { locale: "fr", name: "Albanie", description: "République d'Albanie" },
      { locale: "pt", name: "Albânia", description: "República da Albânia" },
      { locale: "ru", name: "Албания", description: "Республика Албания" },
      { locale: "de", name: "Albanien", description: "Republik Albanien" },
      { locale: "it", name: "Albania", description: "Repubblica d'Albania" },
    ],
  },
  {
    code: "AND",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Andorra", description: "Principality of Andorra" },
      { locale: "ar", name: "أندورا", description: "إمارة أندورا" },
      { locale: "es", name: "Andorra", description: "Principado de Andorra" },
      { locale: "fr", name: "Andorre", description: "Principauté d'Andorre" },
      { locale: "pt", name: "Andorra", description: "Principado de Andorra" },
      { locale: "ru", name: "Андорра", description: "Княжество Андорра" },
      { locale: "de", name: "Andorra", description: "Fürstentum Andorra" },
      { locale: "it", name: "Andorra", description: "Principato di Andorra" },
    ],
  },
  {
    code: "AUT",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Austria", description: "Republic of Austria" },
      { locale: "ar", name: "النمسا", description: "جمهورية النمسا" },
      { locale: "es", name: "Austria", description: "República de Austria" },
      { locale: "fr", name: "Autriche", description: "République d'Autriche" },
      { locale: "pt", name: "Áustria", description: "República da Áustria" },
      { locale: "ru", name: "Австрия", description: "Республика Австрия" },
      { locale: "de", name: "Österreich", description: "Republik Österreich" },
      { locale: "it", name: "Austria", description: "Repubblica d'Austria" },
    ],
  },
  {
    code: "BLR",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Belarus", description: "Republic of Belarus" },
      { locale: "ar", name: "بيلاروسيا", description: "جمهورية بيلاروسيا" },
      {
        locale: "es",
        name: "Bielorrusia",
        description: "República de Belarús",
      },
      {
        locale: "fr",
        name: "Biélorussie",
        description: "République de Biélorussie",
      },
      {
        locale: "pt",
        name: "Bielorrússia",
        description: "República da Bielorrússia",
      },
      { locale: "ru", name: "Беларусь", description: "Республика Беларусь" },
      { locale: "de", name: "Belarus", description: "Republik Belarus" },
      {
        locale: "it",
        name: "Bielorussia",
        description: "Repubblica di Bielorussia",
      },
    ],
  },
  {
    code: "BEL",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Belgium", description: "Kingdom of Belgium" },
      { locale: "ar", name: "بلجيكا", description: "مملكة بلجيكا" },
      { locale: "es", name: "Bélgica", description: "Reino de Bélgica" },
      { locale: "fr", name: "Belgique", description: "Royaume de Belgique" },
      { locale: "pt", name: "Bélgica", description: "Reino da Bélgica" },
      { locale: "ru", name: "Бельгия", description: "Королевство Бельгия" },
      { locale: "de", name: "Belgien", description: "Königreich Belgien" },
      { locale: "it", name: "Belgio", description: "Regno del Belgio" },
    ],
  },
  {
    code: "BIH",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Bosnia and Herzegovina",
        description: "Bosnia and Herzegovina",
      },
      { locale: "ar", name: "البوسنة والهرسك", description: "البوسنة والهرسك" },
      {
        locale: "es",
        name: "Bosnia y Herzegovina",
        description: "Bosnia y Herzegovina",
      },
      {
        locale: "fr",
        name: "Bosnie-Herzégovine",
        description: "Bosnie-Herzégovine",
      },
      {
        locale: "pt",
        name: "Bósnia e Herzegovina",
        description: "Bósnia e Herzegovina",
      },
      {
        locale: "ru",
        name: "Босния и Герцеговина",
        description: "Босния и Герцеговина",
      },
      {
        locale: "de",
        name: "Bosnien und Herzegowina",
        description: "Bosnien und Herzegowina",
      },
      {
        locale: "it",
        name: "Bosnia ed Erzegovina",
        description: "Bosnia ed Erzegovina",
      },
    ],
  },
  {
    code: "BGR",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Bulgaria", description: "Republic of Bulgaria" },
      { locale: "ar", name: "بلغاريا", description: "جمهورية بلغاريا" },
      { locale: "es", name: "Bulgaria", description: "República de Bulgaria" },
      { locale: "fr", name: "Bulgarie", description: "République de Bulgarie" },
      { locale: "pt", name: "Bulgária", description: "República da Bulgária" },
      { locale: "ru", name: "Болгария", description: "Республика Болгария" },
      { locale: "de", name: "Bulgarien", description: "Republik Bulgarien" },
      { locale: "it", name: "Bulgaria", description: "Repubblica di Bulgaria" },
    ],
  },
  {
    code: "HRV",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Croatia", description: "Republic of Croatia" },
      { locale: "ar", name: "كرواتيا", description: "جمهورية كرواتيا" },
      { locale: "es", name: "Croacia", description: "República de Croacia" },
      { locale: "fr", name: "Croatie", description: "République de Croatie" },
      { locale: "pt", name: "Croácia", description: "República da Croácia" },
      { locale: "ru", name: "Хорватия", description: "Республика Хорватия" },
      { locale: "de", name: "Kroatien", description: "Republik Kroatien" },
      { locale: "it", name: "Croazia", description: "Repubblica di Croazia" },
    ],
  },
  {
    code: "CYP",
    continent: "Europe",
    region: "Western Asia",
    isActive: true,
    translations: [
      { locale: "en", name: "Cyprus", description: "Republic of Cyprus" },
      { locale: "ar", name: "قبرص", description: "جمهورية قبرص" },
      { locale: "es", name: "Chipre", description: "República de Chipre" },
      { locale: "fr", name: "Chypre", description: "République de Chypre" },
      { locale: "pt", name: "Chipre", description: "República de Chipre" },
      { locale: "ru", name: "Кипр", description: "Республика Кипр" },
      { locale: "de", name: "Zypern", description: "Republik Zypern" },
      { locale: "it", name: "Cipro", description: "Repubblica di Cipro" },
    ],
  },
  {
    code: "CZE",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Czech Republic", description: "Czech Republic" },
      { locale: "ar", name: "التشيك", description: "جمهورية التشيك" },
      { locale: "es", name: "República Checa", description: "República Checa" },
      {
        locale: "fr",
        name: "République tchèque",
        description: "République tchèque",
      },
      { locale: "pt", name: "República Checa", description: "República Checa" },
      { locale: "ru", name: "Чехия", description: "Чешская Республика" },
      {
        locale: "de",
        name: "Tschechien",
        description: "Tschechische Republik",
      },
      { locale: "it", name: "Repubblica Ceca", description: "Repubblica Ceca" },
    ],
  },
  {
    code: "DNK",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Denmark", description: "Kingdom of Denmark" },
      { locale: "ar", name: "الدنمارك", description: "مملكة الدنمارك" },
      { locale: "es", name: "Dinamarca", description: "Reino de Dinamarca" },
      { locale: "fr", name: "Danemark", description: "Royaume du Danemark" },
      { locale: "pt", name: "Dinamarca", description: "Reino da Dinamarca" },
      { locale: "ru", name: "Дания", description: "Королевство Дания" },
      { locale: "de", name: "Dänemark", description: "Königreich Dänemark" },
      { locale: "it", name: "Danimarca", description: "Regno di Danimarca" },
    ],
  },
  {
    code: "EST",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Estonia", description: "Republic of Estonia" },
      { locale: "ar", name: "إستونيا", description: "جمهورية إستونيا" },
      { locale: "es", name: "Estonia", description: "República de Estonia" },
      { locale: "fr", name: "Estonie", description: "République d'Estonie" },
      { locale: "pt", name: "Estônia", description: "República da Estônia" },
      { locale: "ru", name: "Эстония", description: "Эстонская Республика" },
      { locale: "de", name: "Estland", description: "Republik Estland" },
      { locale: "it", name: "Estonia", description: "Repubblica di Estonia" },
    ],
  },
  {
    code: "FIN",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Finland", description: "Republic of Finland" },
      { locale: "ar", name: "فنلندا", description: "جمهورية فنلندا" },
      {
        locale: "es",
        name: "Finlandia",
        description: "República de Finlandia",
      },
      { locale: "fr", name: "Finlande", description: "République de Finlande" },
      {
        locale: "pt",
        name: "Finlândia",
        description: "República da Finlândia",
      },
      {
        locale: "ru",
        name: "Финляндия",
        description: "Финляндская Республика",
      },
      { locale: "de", name: "Finnland", description: "Republik Finnland" },
      {
        locale: "it",
        name: "Finlandia",
        description: "Repubblica di Finlandia",
      },
    ],
  },
  {
    code: "FRA",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "France", description: "French Republic" },
      { locale: "ar", name: "فرنسا", description: "الجمهورية الفرنسية" },
      { locale: "es", name: "Francia", description: "República Francesa" },
      { locale: "fr", name: "France", description: "République française" },
      { locale: "pt", name: "França", description: "República Francesa" },
      { locale: "ru", name: "Франция", description: "Французская Республика" },
      {
        locale: "de",
        name: "Frankreich",
        description: "Französische Republik",
      },
      { locale: "it", name: "Francia", description: "Repubblica Francese" },
    ],
  },
  {
    code: "DEU",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Germany",
        description: "Federal Republic of Germany",
      },
      {
        locale: "ar",
        name: "ألمانيا",
        description: "جمهورية ألمانيا الاتحادية",
      },
      {
        locale: "es",
        name: "Alemania",
        description: "República Federal de Alemania",
      },
      {
        locale: "fr",
        name: "Allemagne",
        description: "République fédérale d'Allemagne",
      },
      {
        locale: "pt",
        name: "Alemanha",
        description: "República Federal da Alemanha",
      },
      {
        locale: "ru",
        name: "Германия",
        description: "Федеративная Республика Германия",
      },
      {
        locale: "de",
        name: "Deutschland",
        description: "Bundesrepublik Deutschland",
      },
      {
        locale: "it",
        name: "Germania",
        description: "Repubblica Federale di Germania",
      },
    ],
  },
  {
    code: "GRC",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Greece", description: "Hellenic Republic" },
      { locale: "ar", name: "اليونان", description: "الجمهورية الهيلينية" },
      { locale: "es", name: "Grecia", description: "República Helénica" },
      { locale: "fr", name: "Grèce", description: "République hellénique" },
      { locale: "pt", name: "Grécia", description: "República Helênica" },
      { locale: "ru", name: "Греция", description: "Греческая Республика" },
      {
        locale: "de",
        name: "Griechenland",
        description: "Hellenische Republik",
      },
      { locale: "it", name: "Grecia", description: "Repubblica Ellenica" },
    ],
  },
  {
    code: "HUN",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Hungary", description: "Hungary" },
      { locale: "ar", name: "المجر", description: "المجر" },
      { locale: "es", name: "Hungría", description: "Hungría" },
      { locale: "fr", name: "Hongrie", description: "Hongrie" },
      { locale: "pt", name: "Hungria", description: "Hungria" },
      { locale: "ru", name: "Венгрия", description: "Венгрия" },
      { locale: "de", name: "Ungarn", description: "Ungarn" },
      { locale: "it", name: "Ungheria", description: "Ungheria" },
    ],
  },
  {
    code: "ISL",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Iceland", description: "Iceland" },
      { locale: "ar", name: "آيسلندا", description: "آيسلندا" },
      { locale: "es", name: "Islandia", description: "Islandia" },
      { locale: "fr", name: "Islande", description: "Islande" },
      { locale: "pt", name: "Islândia", description: "Islândia" },
      { locale: "ru", name: "Исландия", description: "Исландия" },
      { locale: "de", name: "Island", description: "Island" },
      { locale: "it", name: "Islanda", description: "Islanda" },
    ],
  },
  {
    code: "IRL",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Ireland", description: "Ireland" },
      { locale: "ar", name: "أيرلندا", description: "أيرلندا" },
      { locale: "es", name: "Irlanda", description: "Irlanda" },
      { locale: "fr", name: "Irlande", description: "Irlande" },
      { locale: "pt", name: "Irlanda", description: "Irlanda" },
      { locale: "ru", name: "Ирландия", description: "Ирландия" },
      { locale: "de", name: "Irland", description: "Irland" },
      { locale: "it", name: "Irlanda", description: "Irlanda" },
    ],
  },
  {
    code: "ITA",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Italy", description: "Italian Republic" },
      { locale: "ar", name: "إيطاليا", description: "الجمهورية الإيطالية" },
      { locale: "es", name: "Italia", description: "República Italiana" },
      { locale: "fr", name: "Italie", description: "République italienne" },
      { locale: "pt", name: "Itália", description: "República Italiana" },
      { locale: "ru", name: "Италия", description: "Итальянская Республика" },
      { locale: "de", name: "Italien", description: "Italienische Republik" },
      { locale: "it", name: "Italia", description: "Repubblica Italiana" },
    ],
  },
  {
    code: "LVA",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Latvia", description: "Republic of Latvia" },
      { locale: "ar", name: "لاتفيا", description: "جمهورية لاتفيا" },
      { locale: "es", name: "Letonia", description: "República de Letonia" },
      { locale: "fr", name: "Lettonie", description: "République de Lettonie" },
      { locale: "pt", name: "Letônia", description: "República da Letônia" },
      { locale: "ru", name: "Латвия", description: "Латвийская Республика" },
      { locale: "de", name: "Lettland", description: "Republik Lettland" },
      { locale: "it", name: "Lettonia", description: "Repubblica di Lettonia" },
    ],
  },
  {
    code: "LIE",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Liechtenstein",
        description: "Principality of Liechtenstein",
      },
      { locale: "ar", name: "ليختنشتاين", description: "إمارة ليختنشتاين" },
      {
        locale: "es",
        name: "Liechtenstein",
        description: "Principado de Liechtenstein",
      },
      {
        locale: "fr",
        name: "Liechtenstein",
        description: "Principauté du Liechtenstein",
      },
      {
        locale: "pt",
        name: "Liechtenstein",
        description: "Principado de Liechtenstein",
      },
      {
        locale: "ru",
        name: "Лихтенштейн",
        description: "Княжество Лихтенштейн",
      },
      {
        locale: "de",
        name: "Liechtenstein",
        description: "Fürstentum Liechtenstein",
      },
      {
        locale: "it",
        name: "Liechtenstein",
        description: "Principato del Liechtenstein",
      },
    ],
  },
  {
    code: "LTU",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Lithuania", description: "Republic of Lithuania" },
      { locale: "ar", name: "ليتوانيا", description: "جمهورية ليتوانيا" },
      { locale: "es", name: "Lituania", description: "República de Lituania" },
      { locale: "fr", name: "Lituanie", description: "République de Lituanie" },
      { locale: "pt", name: "Lituânia", description: "República da Lituânia" },
      { locale: "ru", name: "Литва", description: "Литовская Республика" },
      { locale: "de", name: "Litauen", description: "Republik Litauen" },
      { locale: "it", name: "Lituania", description: "Repubblica di Lituania" },
    ],
  },
  {
    code: "LUX",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Luxembourg",
        description: "Grand Duchy of Luxembourg",
      },
      {
        locale: "ar",
        name: "لوكسمبورغ",
        description: "دوقية لوكسمبورغ الكبرى",
      },
      {
        locale: "es",
        name: "Luxemburgo",
        description: "Gran Ducado de Luxemburgo",
      },
      {
        locale: "fr",
        name: "Luxembourg",
        description: "Grand-Duché de Luxembourg",
      },
      {
        locale: "pt",
        name: "Luxemburgo",
        description: "Grão-Ducado do Luxemburgo",
      },
      {
        locale: "ru",
        name: "Люксембург",
        description: "Великое Герцогство Люксембург",
      },
      {
        locale: "de",
        name: "Luxemburg",
        description: "Großherzogtum Luxemburg",
      },
      {
        locale: "it",
        name: "Lussemburgo",
        description: "Granducato di Lussemburgo",
      },
    ],
  },
  {
    code: "MLT",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Malta", description: "Republic of Malta" },
      { locale: "ar", name: "مالطا", description: "جمهورية مالطا" },
      { locale: "es", name: "Malta", description: "República de Malta" },
      { locale: "fr", name: "Malte", description: "République de Malte" },
      { locale: "pt", name: "Malta", description: "República de Malta" },
      { locale: "ru", name: "Мальта", description: "Республика Мальта" },
      { locale: "de", name: "Malta", description: "Republik Malta" },
      { locale: "it", name: "Malta", description: "Repubblica di Malta" },
    ],
  },
  {
    code: "MDA",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Moldova", description: "Republic of Moldova" },
      { locale: "ar", name: "مولدوفا", description: "جمهورية مولدوفا" },
      { locale: "es", name: "Moldavia", description: "República de Moldavia" },
      { locale: "fr", name: "Moldavie", description: "République de Moldavie" },
      { locale: "pt", name: "Moldávia", description: "República da Moldávia" },
      { locale: "ru", name: "Молдова", description: "Республика Молдова" },
      { locale: "de", name: "Moldau", description: "Republik Moldau" },
      { locale: "it", name: "Moldova", description: "Repubblica di Moldova" },
    ],
  },
  {
    code: "MCO",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Monaco", description: "Principality of Monaco" },
      { locale: "ar", name: "موناكو", description: "إمارة موناكو" },
      { locale: "es", name: "Mónaco", description: "Principado de Mónaco" },
      { locale: "fr", name: "Monaco", description: "Principauté de Monaco" },
      { locale: "pt", name: "Mônaco", description: "Principado do Mônaco" },
      { locale: "ru", name: "Монако", description: "Княжество Монако" },
      { locale: "de", name: "Monaco", description: "Fürstentum Monaco" },
      { locale: "it", name: "Monaco", description: "Principato di Monaco" },
    ],
  },
  {
    code: "MNE",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Montenegro", description: "Montenegro" },
      { locale: "ar", name: "الجبل الأسود", description: "الجبل الأسود" },
      { locale: "es", name: "Montenegro", description: "Montenegro" },
      { locale: "fr", name: "Monténégro", description: "Monténégro" },
      { locale: "pt", name: "Montenegro", description: "Montenegro" },
      { locale: "ru", name: "Черногория", description: "Черногория" },
      { locale: "de", name: "Montenegro", description: "Montenegro" },
      { locale: "it", name: "Montenegro", description: "Montenegro" },
    ],
  },
  {
    code: "NLD",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Netherlands",
        description: "Kingdom of the Netherlands",
      },
      { locale: "ar", name: "هولندا", description: "مملكة هولندا" },
      {
        locale: "es",
        name: "Países Bajos",
        description: "Reino de los Países Bajos",
      },
      { locale: "fr", name: "Pays-Bas", description: "Royaume des Pays-Bas" },
      {
        locale: "pt",
        name: "Países Baixos",
        description: "Reino dos Países Baixos",
      },
      {
        locale: "ru",
        name: "Нидерланды",
        description: "Королевство Нидерландов",
      },
      {
        locale: "de",
        name: "Niederlande",
        description: "Königreich der Niederlande",
      },
      {
        locale: "it",
        name: "Paesi Bassi",
        description: "Regno dei Paesi Bassi",
      },
    ],
  },
  {
    code: "MKD",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "North Macedonia",
        description: "Republic of North Macedonia",
      },
      {
        locale: "ar",
        name: "مقدونيا الشمالية",
        description: "جمهورية مقدونيا الشمالية",
      },
      {
        locale: "es",
        name: "Macedonia del Norte",
        description: "República de Macedonia del Norte",
      },
      {
        locale: "fr",
        name: "Macédoine du Nord",
        description: "République de Macédoine du Nord",
      },
      {
        locale: "pt",
        name: "Macedônia do Norte",
        description: "República da Macedônia do Norte",
      },
      {
        locale: "ru",
        name: "Северная Македония",
        description: "Республика Северная Македония",
      },
      {
        locale: "de",
        name: "Nordmazedonien",
        description: "Republik Nordmazedonien",
      },
      {
        locale: "it",
        name: "Macedonia del Nord",
        description: "Repubblica di Macedonia del Nord",
      },
    ],
  },
  {
    code: "NOR",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Norway", description: "Kingdom of Norway" },
      { locale: "ar", name: "النرويج", description: "مملكة النرويج" },
      { locale: "es", name: "Noruega", description: "Reino de Noruega" },
      { locale: "fr", name: "Norvège", description: "Royaume de Norvège" },
      { locale: "pt", name: "Noruega", description: "Reino da Noruega" },
      { locale: "ru", name: "Норвегия", description: "Королевство Норвегия" },
      { locale: "de", name: "Norwegen", description: "Königreich Norwegen" },
      { locale: "it", name: "Norvegia", description: "Regno di Norvegia" },
    ],
  },
  {
    code: "POL",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Poland", description: "Republic of Poland" },
      { locale: "ar", name: "بولندا", description: "جمهورية بولندا" },
      { locale: "es", name: "Polonia", description: "República de Polonia" },
      { locale: "fr", name: "Pologne", description: "République de Pologne" },
      { locale: "pt", name: "Polônia", description: "República da Polônia" },
      { locale: "ru", name: "Польша", description: "Республика Польша" },
      { locale: "de", name: "Polen", description: "Republik Polen" },
      { locale: "it", name: "Polonia", description: "Repubblica di Polonia" },
    ],
  },
  {
    code: "PRT",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Portugal", description: "Portuguese Republic" },
      { locale: "ar", name: "البرتغال", description: "الجمهورية البرتغالية" },
      { locale: "es", name: "Portugal", description: "República Portuguesa" },
      { locale: "fr", name: "Portugal", description: "République portugaise" },
      { locale: "pt", name: "Portugal", description: "República Portuguesa" },
      {
        locale: "ru",
        name: "Португалия",
        description: "Португальская Республика",
      },
      {
        locale: "de",
        name: "Portugal",
        description: "Portugiesische Republik",
      },
      {
        locale: "it",
        name: "Portogallo",
        description: "Repubblica Portoghese",
      },
    ],
  },
  {
    code: "ROU",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Romania", description: "Romania" },
      { locale: "ar", name: "رومانيا", description: "رومانيا" },
      { locale: "es", name: "Rumania", description: "Rumania" },
      { locale: "fr", name: "Roumanie", description: "Roumanie" },
      { locale: "pt", name: "Romênia", description: "Romênia" },
      { locale: "ru", name: "Румыния", description: "Румыния" },
      { locale: "de", name: "Rumänien", description: "Rumänien" },
      { locale: "it", name: "Romania", description: "Romania" },
    ],
  },
  {
    code: "RUS",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Russia", description: "Russian Federation" },
      { locale: "ar", name: "روسيا", description: "الاتحاد الروسي" },
      { locale: "es", name: "Rusia", description: "Federación de Rusia" },
      { locale: "fr", name: "Russie", description: "Fédération de Russie" },
      { locale: "pt", name: "Rússia", description: "Federação Russa" },
      { locale: "ru", name: "Россия", description: "Российская Федерация" },
      { locale: "de", name: "Russland", description: "Russische Föderation" },
      { locale: "it", name: "Russia", description: "Federazione Russa" },
    ],
  },
  {
    code: "SMR",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "San Marino",
        description: "Republic of San Marino",
      },
      { locale: "ar", name: "سان مارينو", description: "جمهورية سان مارينو" },
      {
        locale: "es",
        name: "San Marino",
        description: "República de San Marino",
      },
      {
        locale: "fr",
        name: "Saint-Marin",
        description: "République de Saint-Marin",
      },
      {
        locale: "pt",
        name: "San Marino",
        description: "República de San Marino",
      },
      {
        locale: "ru",
        name: "Сан-Марино",
        description: "Республика Сан-Марино",
      },
      { locale: "de", name: "San Marino", description: "Republik San Marino" },
      {
        locale: "it",
        name: "San Marino",
        description: "Repubblica di San Marino",
      },
    ],
  },
  {
    code: "SRB",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Serbia", description: "Republic of Serbia" },
      { locale: "ar", name: "صربيا", description: "جمهورية صربيا" },
      { locale: "es", name: "Serbia", description: "República de Serbia" },
      { locale: "fr", name: "Serbie", description: "République de Serbie" },
      { locale: "pt", name: "Sérvia", description: "República da Sérvia" },
      { locale: "ru", name: "Сербия", description: "Республика Сербия" },
      { locale: "de", name: "Serbien", description: "Republik Serbien" },
      { locale: "it", name: "Serbia", description: "Repubblica di Serbia" },
    ],
  },
  {
    code: "SVK",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Slovakia", description: "Slovak Republic" },
      { locale: "ar", name: "سلوفاكيا", description: "جمهورية سلوفاكيا" },
      { locale: "es", name: "Eslovaquia", description: "República Eslovaca" },
      { locale: "fr", name: "Slovaquie", description: "République slovaque" },
      { locale: "pt", name: "Eslováquia", description: "República Eslovaca" },
      { locale: "ru", name: "Словакия", description: "Словацкая Республика" },
      { locale: "de", name: "Slowakei", description: "Slowakische Republik" },
      { locale: "it", name: "Slovacchia", description: "Repubblica Slovacca" },
    ],
  },
  {
    code: "SVN",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Slovenia", description: "Republic of Slovenia" },
      { locale: "ar", name: "سلوفينيا", description: "جمهورية سلوفينيا" },
      {
        locale: "es",
        name: "Eslovenia",
        description: "República de Eslovenia",
      },
      { locale: "fr", name: "Slovénie", description: "République de Slovénie" },
      {
        locale: "pt",
        name: "Eslovênia",
        description: "República da Eslovênia",
      },
      { locale: "ru", name: "Словения", description: "Республика Словения" },
      { locale: "de", name: "Slowenien", description: "Republik Slowenien" },
      { locale: "it", name: "Slovenia", description: "Repubblica di Slovenia" },
    ],
  },
  {
    code: "ESP",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Spain", description: "Kingdom of Spain" },
      { locale: "ar", name: "إسبانيا", description: "مملكة إسبانيا" },
      { locale: "es", name: "España", description: "Reino de España" },
      { locale: "fr", name: "Espagne", description: "Royaume d'Espagne" },
      { locale: "pt", name: "Espanha", description: "Reino de Espanha" },
      { locale: "ru", name: "Испания", description: "Королевство Испания" },
      { locale: "de", name: "Spanien", description: "Königreich Spanien" },
      { locale: "it", name: "Spagna", description: "Regno di Spagna" },
    ],
  },
  {
    code: "SWE",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Sweden", description: "Kingdom of Sweden" },
      { locale: "ar", name: "السويد", description: "مملكة السويد" },
      { locale: "es", name: "Suecia", description: "Reino de Suecia" },
      { locale: "fr", name: "Suède", description: "Royaume de Suède" },
      { locale: "pt", name: "Suécia", description: "Reino da Suécia" },
      { locale: "ru", name: "Швеция", description: "Королевство Швеция" },
      { locale: "de", name: "Schweden", description: "Königreich Schweden" },
      { locale: "it", name: "Svezia", description: "Regno di Svezia" },
    ],
  },
  {
    code: "CHE",
    continent: "Europe",
    region: "Western Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Switzerland", description: "Swiss Confederation" },
      { locale: "ar", name: "سويسرا", description: "الاتحاد السويسري" },
      { locale: "es", name: "Suiza", description: "Confederación Suiza" },
      { locale: "fr", name: "Suisse", description: "Confédération suisse" },
      { locale: "pt", name: "Suíça", description: "Confederação Suíça" },
      {
        locale: "ru",
        name: "Швейцария",
        description: "Швейцарская Конфедерация",
      },
      {
        locale: "de",
        name: "Schweiz",
        description: "Schweizerische Eidgenossenschaft",
      },
      {
        locale: "it",
        name: "Svizzera",
        description: "Confederazione Svizzera",
      },
    ],
  },
  {
    code: "UKR",
    continent: "Europe",
    region: "Eastern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Ukraine", description: "Ukraine" },
      { locale: "ar", name: "أوكرانيا", description: "أوكرانيا" },
      { locale: "es", name: "Ucrania", description: "Ucrania" },
      { locale: "fr", name: "Ukraine", description: "Ukraine" },
      { locale: "pt", name: "Ucrânia", description: "Ucrânia" },
      { locale: "ru", name: "Украина", description: "Украина" },
      { locale: "de", name: "Ukraine", description: "Ukraine" },
      { locale: "it", name: "Ucraina", description: "Ucraina" },
    ],
  },
  {
    code: "GBR",
    continent: "Europe",
    region: "Northern Europe",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "United Kingdom",
        description: "United Kingdom of Great Britain and Northern Ireland",
      },
      {
        locale: "ar",
        name: "المملكة المتحدة",
        description: "المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية",
      },
      {
        locale: "es",
        name: "Reino Unido",
        description: "Reino Unido de Gran Bretaña e Irlanda del Norte",
      },
      {
        locale: "fr",
        name: "Royaume-Uni",
        description: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
      },
      {
        locale: "pt",
        name: "Reino Unido",
        description: "Reino Unido da Grã-Bretanha e Irlanda do Norte",
      },
      {
        locale: "ru",
        name: "Великобритания",
        description:
          "Соединенное Королевство Великобритании и Северной Ирландии",
      },
      {
        locale: "de",
        name: "Vereinigtes Königreich",
        description: "Vereinigtes Königreich Großbritannien und Nordirland",
      },
      {
        locale: "it",
        name: "Regno Unito",
        description: "Regno Unito di Gran Bretagna e Irlanda del Nord",
      },
    ],
  },
  {
    code: "VAT",
    continent: "Europe",
    region: "Southern Europe",
    isActive: true,
    translations: [
      { locale: "en", name: "Vatican City", description: "Vatican City State" },
      { locale: "ar", name: "الفاتيكان", description: "دولة الفاتيكان" },
      {
        locale: "es",
        name: "Ciudad del Vaticano",
        description: "Estado de la Ciudad del Vaticano",
      },
      {
        locale: "fr",
        name: "Vatican",
        description: "État de la Cité du Vatican",
      },
      {
        locale: "pt",
        name: "Vaticano",
        description: "Estado da Cidade do Vaticano",
      },
      {
        locale: "ru",
        name: "Ватикан",
        description: "Государство-город Ватикан",
      },
      { locale: "de", name: "Vatikan", description: "Vatikanstadt" },
      {
        locale: "it",
        name: "Vaticano",
        description: "Stato della Città del Vaticano",
      },
    ],
  },
];
