/**
 * Comprehensive list of all world countries with ISO 3166-1 alpha-3 codes
 * Includes continent and region information for database seeding
 */

export interface CountryData {
  code: string; // ISO 3166-1 alpha-3
  continent: string;
  region: string;
  isActive: boolean;
  translations: {
    locale: string;
    name: string;
    description: string;
  }[];
}

export const allCountriesData: CountryData[] = [
  // Africa
  {
    code: "DZA",
    continent: "Africa",
    region: "Northern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Algeria",
        description: "People's Democratic Republic of Algeria",
      },
      {
        locale: "ar",
        name: "الجزائر",
        description: "الجمهورية الجزائرية الديمقراطية الشعبية",
      },
      {
        locale: "es",
        name: "Argelia",
        description: "República Argelina Democrática y Popular",
      },
      {
        locale: "fr",
        name: "Algérie",
        description: "République algérienne démocratique et populaire",
      },
      {
        locale: "pt",
        name: "Argélia",
        description: "República Argelina Democrática e Popular",
      },
      {
        locale: "ru",
        name: "Алжир",
        description: "Алжирская Народно-Демократическая Республика",
      },
      {
        locale: "de",
        name: "Algerien",
        description: "Demokratische Volksrepublik Algerien",
      },
      {
        locale: "it",
        name: "Algeria",
        description: "Repubblica Algerina Democratica e Popolare",
      },
    ],
  },
  {
    code: "AGO",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Angola", description: "Republic of Angola" },
      { locale: "ar", name: "أنغولا", description: "جمهورية أنغولا" },
      { locale: "es", name: "Angola", description: "República de Angola" },
      { locale: "fr", name: "Angola", description: "République d'Angola" },
      { locale: "pt", name: "Angola", description: "República de Angola" },
      { locale: "ru", name: "Ангола", description: "Республика Ангола" },
      { locale: "de", name: "Angola", description: "Republik Angola" },
      { locale: "it", name: "Angola", description: "Repubblica dell'Angola" },
    ],
  },
  {
    code: "BEN",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Benin", description: "Republic of Benin" },
      { locale: "ar", name: "بنين", description: "جمهورية بنين" },
      { locale: "es", name: "Benín", description: "República de Benín" },
      { locale: "fr", name: "Bénin", description: "République du Bénin" },
      { locale: "pt", name: "Benin", description: "República do Benin" },
      { locale: "ru", name: "Бенин", description: "Республика Бенин" },
      { locale: "de", name: "Benin", description: "Republik Benin" },
      { locale: "it", name: "Benin", description: "Repubblica del Benin" },
    ],
  },
  {
    code: "BWA",
    continent: "Africa",
    region: "Southern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Botswana", description: "Republic of Botswana" },
      { locale: "ar", name: "بوتسوانا", description: "جمهورية بوتسوانا" },
      { locale: "es", name: "Botsuana", description: "República de Botsuana" },
      { locale: "fr", name: "Botswana", description: "République du Botswana" },
      { locale: "pt", name: "Botsuana", description: "República do Botsuana" },
      { locale: "ru", name: "Ботсвана", description: "Республика Ботсвана" },
      { locale: "de", name: "Botswana", description: "Republik Botswana" },
      {
        locale: "it",
        name: "Botswana",
        description: "Repubblica del Botswana",
      },
    ],
  },
  {
    code: "BFA",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Burkina Faso", description: "Burkina Faso" },
      { locale: "ar", name: "بوركينا فاسو", description: "بوركينا فاسو" },
      { locale: "es", name: "Burkina Faso", description: "Burkina Faso" },
      { locale: "fr", name: "Burkina Faso", description: "Burkina Faso" },
      { locale: "pt", name: "Burkina Faso", description: "Burkina Faso" },
      { locale: "ru", name: "Буркина-Фасо", description: "Буркина-Фасо" },
      { locale: "de", name: "Burkina Faso", description: "Burkina Faso" },
      { locale: "it", name: "Burkina Faso", description: "Burkina Faso" },
    ],
  },
  {
    code: "BDI",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Burundi", description: "Republic of Burundi" },
      { locale: "ar", name: "بوروندي", description: "جمهورية بوروندي" },
      { locale: "es", name: "Burundi", description: "República de Burundi" },
      { locale: "fr", name: "Burundi", description: "République du Burundi" },
      { locale: "pt", name: "Burundi", description: "República do Burundi" },
      { locale: "ru", name: "Бурунди", description: "Республика Бурунди" },
      { locale: "de", name: "Burundi", description: "Republik Burundi" },
      { locale: "it", name: "Burundi", description: "Repubblica del Burundi" },
    ],
  },
  {
    code: "CMR",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Cameroon", description: "Republic of Cameroon" },
      { locale: "ar", name: "الكاميرون", description: "جمهورية الكاميرون" },
      { locale: "es", name: "Camerún", description: "República de Camerún" },
      { locale: "fr", name: "Cameroun", description: "République du Cameroun" },
      { locale: "pt", name: "Camarões", description: "República dos Camarões" },
      { locale: "ru", name: "Камерун", description: "Республика Камерун" },
      { locale: "de", name: "Kamerun", description: "Republik Kamerun" },
      { locale: "it", name: "Camerun", description: "Repubblica del Camerun" },
    ],
  },
  {
    code: "CPV",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Cape Verde",
        description: "Republic of Cabo Verde",
      },
      {
        locale: "ar",
        name: "الرأس الأخضر",
        description: "جمهورية الرأس الأخضر",
      },
      {
        locale: "es",
        name: "Cabo Verde",
        description: "República de Cabo Verde",
      },
      { locale: "fr", name: "Cap-Vert", description: "République du Cap-Vert" },
      {
        locale: "pt",
        name: "Cabo Verde",
        description: "República de Cabo Verde",
      },
      {
        locale: "ru",
        name: "Кабо-Верде",
        description: "Республика Кабо-Верде",
      },
      { locale: "de", name: "Kap Verde", description: "Republik Kap Verde" },
      {
        locale: "it",
        name: "Capo Verde",
        description: "Repubblica di Capo Verde",
      },
    ],
  },
  {
    code: "CAF",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Central African Republic",
        description: "Central African Republic",
      },
      {
        locale: "ar",
        name: "جمهورية أفريقيا الوسطى",
        description: "جمهورية أفريقيا الوسطى",
      },
      {
        locale: "es",
        name: "República Centroafricana",
        description: "República Centroafricana",
      },
      {
        locale: "fr",
        name: "République centrafricaine",
        description: "République centrafricaine",
      },
      {
        locale: "pt",
        name: "República Centro-Africana",
        description: "República Centro-Africana",
      },
      {
        locale: "ru",
        name: "Центральноафриканская Республика",
        description: "Центральноафриканская Республика",
      },
      {
        locale: "de",
        name: "Zentralafrikanische Republik",
        description: "Zentralafrikanische Republik",
      },
      {
        locale: "it",
        name: "Repubblica Centrafricana",
        description: "Repubblica Centrafricana",
      },
    ],
  },
  {
    code: "TCD",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Chad", description: "Republic of Chad" },
      { locale: "ar", name: "تشاد", description: "جمهورية تشاد" },
      { locale: "es", name: "Chad", description: "República del Chad" },
      { locale: "fr", name: "Tchad", description: "République du Tchad" },
      { locale: "pt", name: "Chade", description: "República do Chade" },
      { locale: "ru", name: "Чад", description: "Республика Чад" },
      { locale: "de", name: "Tschad", description: "Republik Tschad" },
      { locale: "it", name: "Ciad", description: "Repubblica del Ciad" },
    ],
  },
  {
    code: "COM",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Comoros", description: "Union of the Comoros" },
      { locale: "ar", name: "جزر القمر", description: "اتحاد جزر القمر" },
      { locale: "es", name: "Comoras", description: "Unión de las Comoras" },
      { locale: "fr", name: "Comores", description: "Union des Comores" },
      { locale: "pt", name: "Comores", description: "União das Comores" },
      { locale: "ru", name: "Коморы", description: "Союз Коморских Островов" },
      { locale: "de", name: "Komoren", description: "Union der Komoren" },
      { locale: "it", name: "Comore", description: "Unione delle Comore" },
    ],
  },
  {
    code: "COG",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Congo", description: "Republic of the Congo" },
      { locale: "ar", name: "الكونغو", description: "جمهورية الكونغو" },
      { locale: "es", name: "Congo", description: "República del Congo" },
      { locale: "fr", name: "Congo", description: "République du Congo" },
      { locale: "pt", name: "Congo", description: "República do Congo" },
      { locale: "ru", name: "Конго", description: "Республика Конго" },
      { locale: "de", name: "Kongo", description: "Republik Kongo" },
      { locale: "it", name: "Congo", description: "Repubblica del Congo" },
    ],
  },
  {
    code: "COD",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Democratic Republic of the Congo",
        description: "Democratic Republic of the Congo",
      },
      {
        locale: "ar",
        name: "جمهورية الكونغو الديمقراطية",
        description: "جمهورية الكونغو الديمقراطية",
      },
      {
        locale: "es",
        name: "República Democrática del Congo",
        description: "República Democrática del Congo",
      },
      {
        locale: "fr",
        name: "République démocratique du Congo",
        description: "République démocratique du Congo",
      },
      {
        locale: "pt",
        name: "República Democrática do Congo",
        description: "República Democrática do Congo",
      },
      {
        locale: "ru",
        name: "Демократическая Республика Конго",
        description: "Демократическая Республика Конго",
      },
      {
        locale: "de",
        name: "Demokratische Republik Kongo",
        description: "Demokratische Republik Kongo",
      },
      {
        locale: "it",
        name: "Repubblica Democratica del Congo",
        description: "Repubblica Democratica del Congo",
      },
    ],
  },
  {
    code: "CIV",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Côte d'Ivoire",
        description: "Republic of Côte d'Ivoire",
      },
      { locale: "ar", name: "ساحل العاج", description: "جمهورية ساحل العاج" },
      {
        locale: "es",
        name: "Costa de Marfil",
        description: "República de Côte d'Ivoire",
      },
      {
        locale: "fr",
        name: "Côte d'Ivoire",
        description: "République de Côte d'Ivoire",
      },
      {
        locale: "pt",
        name: "Costa do Marfim",
        description: "República da Costa do Marfim",
      },
      {
        locale: "ru",
        name: "Кот-д'Ивуар",
        description: "Республика Кот-д'Ивуар",
      },
      {
        locale: "de",
        name: "Elfenbeinküste",
        description: "Republik Côte d'Ivoire",
      },
      {
        locale: "it",
        name: "Costa d'Avorio",
        description: "Repubblica della Costa d'Avorio",
      },
    ],
  },
  {
    code: "DJI",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Djibouti", description: "Republic of Djibouti" },
      { locale: "ar", name: "جيبوتي", description: "جمهورية جيبوتي" },
      { locale: "es", name: "Yibuti", description: "República de Yibuti" },
      { locale: "fr", name: "Djibouti", description: "République de Djibouti" },
      { locale: "pt", name: "Djibuti", description: "República do Djibuti" },
      { locale: "ru", name: "Джибути", description: "Республика Джибути" },
      { locale: "de", name: "Dschibuti", description: "Republik Dschibuti" },
      { locale: "it", name: "Gibuti", description: "Repubblica di Gibuti" },
    ],
  },
  {
    code: "EGY",
    continent: "Africa",
    region: "Northern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Egypt", description: "Arab Republic of Egypt" },
      { locale: "ar", name: "مصر", description: "جمهورية مصر العربية" },
      {
        locale: "es",
        name: "Egipto",
        description: "República Árabe de Egipto",
      },
      {
        locale: "fr",
        name: "Égypte",
        description: "République arabe d'Égypte",
      },
      {
        locale: "pt",
        name: "Egito",
        description: "República Árabe do Egito",
      },
      {
        locale: "ru",
        name: "Египет",
        description: "Арабская Республика Египет",
      },
      {
        locale: "de",
        name: "Ägypten",
        description: "Arabische Republik Ägypten",
      },
      {
        locale: "it",
        name: "Egitto",
        description: "Repubblica Araba d'Egitto",
      },
    ],
  },
  {
    code: "GNQ",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Equatorial Guinea",
        description: "Republic of Equatorial Guinea",
      },
      {
        locale: "ar",
        name: "غينيا الاستوائية",
        description: "جمهورية غينيا الاستوائية",
      },
      {
        locale: "es",
        name: "Guinea Ecuatorial",
        description: "República de Guinea Ecuatorial",
      },
      {
        locale: "fr",
        name: "Guinée équatoriale",
        description: "République de Guinée équatoriale",
      },
      {
        locale: "pt",
        name: "Guiné Equatorial",
        description: "República da Guiné Equatorial",
      },
      {
        locale: "ru",
        name: "Экваториальная Гвинея",
        description: "Республика Экваториальная Гвинея",
      },
      {
        locale: "de",
        name: "Äquatorialguinea",
        description: "Republik Äquatorialguinea",
      },
      {
        locale: "it",
        name: "Guinea Equatoriale",
        description: "Repubblica della Guinea Equatoriale",
      },
    ],
  },
  {
    code: "ERI",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Eritrea", description: "State of Eritrea" },
      { locale: "ar", name: "إريتريا", description: "دولة إريتريا" },
      { locale: "es", name: "Eritrea", description: "Estado de Eritrea" },
      { locale: "fr", name: "Érythrée", description: "État d'Érythrée" },
      { locale: "pt", name: "Eritreia", description: "Estado da Eritreia" },
      { locale: "ru", name: "Эритрея", description: "Государство Эритрея" },
      { locale: "de", name: "Eritrea", description: "Staat Eritrea" },
      { locale: "it", name: "Eritrea", description: "Stato dell'Eritrea" },
    ],
  },
  {
    code: "SWZ",
    continent: "Africa",
    region: "Southern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Eswatini", description: "Kingdom of Eswatini" },
      { locale: "ar", name: "إسواتيني", description: "مملكة إسواتيني" },
      { locale: "es", name: "Esuatini", description: "Reino de Esuatini" },
      { locale: "fr", name: "Eswatini", description: "Royaume d'Eswatini" },
      { locale: "pt", name: "Eswatini", description: "Reino de Eswatini" },
      { locale: "ru", name: "Эсватини", description: "Королевство Эсватини" },
      { locale: "de", name: "Eswatini", description: "Königreich Eswatini" },
      { locale: "it", name: "Eswatini", description: "Regno di Eswatini" },
    ],
  },
  {
    code: "ETH",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Ethiopia",
        description: "Federal Democratic Republic of Ethiopia",
      },
      {
        locale: "ar",
        name: "إثيوبيا",
        description: "جمهورية إثيوبيا الفيدرالية الديمقراطية",
      },
      {
        locale: "es",
        name: "Etiopía",
        description: "República Democrática Federal de Etiopía",
      },
      {
        locale: "fr",
        name: "Éthiopie",
        description: "République fédérale démocratique d'Éthiopie",
      },
      {
        locale: "pt",
        name: "Etiópia",
        description: "República Democrática Federal da Etiópia",
      },
      {
        locale: "ru",
        name: "Эфиопия",
        description: "Федеративная Демократическая Республика Эфиопия",
      },
      {
        locale: "de",
        name: "Äthiopien",
        description: "Demokratische Bundesrepublik Äthiopien",
      },
      {
        locale: "it",
        name: "Etiopia",
        description: "Repubblica Federale Democratica d'Etiopia",
      },
    ],
  },
  {
    code: "GAB",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Gabon", description: "Gabonese Republic" },
      { locale: "ar", name: "الغابون", description: "جمهورية الغابون" },
      { locale: "es", name: "Gabón", description: "República Gabonesa" },
      { locale: "fr", name: "Gabon", description: "République gabonaise" },
      { locale: "pt", name: "Gabão", description: "República Gabonesa" },
      { locale: "ru", name: "Габон", description: "Габонская Республика" },
      { locale: "de", name: "Gabun", description: "Gabunische Republik" },
      { locale: "it", name: "Gabon", description: "Repubblica Gabonese" },
    ],
  },
  {
    code: "GMB",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Gambia", description: "Republic of the Gambia" },
      { locale: "ar", name: "غامبيا", description: "جمهورية غامبيا" },
      { locale: "es", name: "Gambia", description: "República de Gambia" },
      { locale: "fr", name: "Gambie", description: "République de Gambie" },
      { locale: "pt", name: "Gâmbia", description: "República da Gâmbia" },
      { locale: "ru", name: "Гамбия", description: "Республика Гамбия" },
      { locale: "de", name: "Gambia", description: "Republik Gambia" },
      { locale: "it", name: "Gambia", description: "Repubblica del Gambia" },
    ],
  },
  {
    code: "GHA",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Ghana", description: "Republic of Ghana" },
      { locale: "ar", name: "غانا", description: "جمهورية غانا" },
      { locale: "es", name: "Ghana", description: "República de Ghana" },
      { locale: "fr", name: "Ghana", description: "République du Ghana" },
      { locale: "pt", name: "Gana", description: "República do Gana" },
      { locale: "ru", name: "Гана", description: "Республика Гана" },
      { locale: "de", name: "Ghana", description: "Republik Ghana" },
      { locale: "it", name: "Ghana", description: "Repubblica del Ghana" },
    ],
  },
  {
    code: "GIN",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Guinea", description: "Republic of Guinea" },
      { locale: "ar", name: "غينيا", description: "جمهورية غينيا" },
      { locale: "es", name: "Guinea", description: "República de Guinea" },
      { locale: "fr", name: "Guinée", description: "République de Guinée" },
      { locale: "pt", name: "Guiné", description: "República da Guiné" },
      { locale: "ru", name: "Гвинея", description: "Республика Гвинея" },
      { locale: "de", name: "Guinea", description: "Republik Guinea" },
      { locale: "it", name: "Guinea", description: "Repubblica di Guinea" },
    ],
  },
  {
    code: "GNB",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Guinea-Bissau",
        description: "Republic of Guinea-Bissau",
      },
      { locale: "ar", name: "غينيا بيساو", description: "جمهورية غينيا بيساو" },
      {
        locale: "es",
        name: "Guinea-Bisáu",
        description: "República de Guinea-Bisáu",
      },
      {
        locale: "fr",
        name: "Guinée-Bissau",
        description: "République de Guinée-Bissau",
      },
      {
        locale: "pt",
        name: "Guiné-Bissau",
        description: "República da Guiné-Bissau",
      },
      {
        locale: "ru",
        name: "Гвинея-Бисау",
        description: "Республика Гвинея-Бисау",
      },
      {
        locale: "de",
        name: "Guinea-Bissau",
        description: "Republik Guinea-Bissau",
      },
      {
        locale: "it",
        name: "Guinea-Bissau",
        description: "Repubblica della Guinea-Bissau",
      },
    ],
  },
  {
    code: "KEN",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Kenya", description: "Republic of Kenya" },
      { locale: "ar", name: "كينيا", description: "جمهورية كينيا" },
      { locale: "es", name: "Kenia", description: "República de Kenia" },
      { locale: "fr", name: "Kenya", description: "République du Kenya" },
      { locale: "pt", name: "Quênia", description: "República do Quênia" },
      { locale: "ru", name: "Кения", description: "Республика Кения" },
      { locale: "de", name: "Kenia", description: "Republik Kenia" },
      { locale: "it", name: "Kenya", description: "Repubblica del Kenya" },
    ],
  },
  {
    code: "LSO",
    continent: "Africa",
    region: "Southern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Lesotho", description: "Kingdom of Lesotho" },
      { locale: "ar", name: "ليسوتو", description: "مملكة ليسوتو" },
      { locale: "es", name: "Lesoto", description: "Reino de Lesoto" },
      { locale: "fr", name: "Lesotho", description: "Royaume du Lesotho" },
      { locale: "pt", name: "Lesoto", description: "Reino do Lesoto" },
      { locale: "ru", name: "Лесото", description: "Королевство Лесото" },
      { locale: "de", name: "Lesotho", description: "Königreich Lesotho" },
      { locale: "it", name: "Lesotho", description: "Regno del Lesotho" },
    ],
  },
  {
    code: "LBR",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Liberia", description: "Republic of Liberia" },
      { locale: "ar", name: "ليبيريا", description: "جمهورية ليبيريا" },
      { locale: "es", name: "Liberia", description: "República de Liberia" },
      { locale: "fr", name: "Libéria", description: "République du Libéria" },
      { locale: "pt", name: "Libéria", description: "República da Libéria" },
      { locale: "ru", name: "Либерия", description: "Республика Либерия" },
      { locale: "de", name: "Liberia", description: "Republik Liberia" },
      { locale: "it", name: "Liberia", description: "Repubblica di Liberia" },
    ],
  },
  {
    code: "LBY",
    continent: "Africa",
    region: "Northern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Libya", description: "State of Libya" },
      { locale: "ar", name: "ليبيا", description: "دولة ليبيا" },
      { locale: "es", name: "Libia", description: "Estado de Libia" },
      { locale: "fr", name: "Libye", description: "État de Libye" },
      { locale: "pt", name: "Líbia", description: "Estado da Líbia" },
      { locale: "ru", name: "Ливия", description: "Государство Ливия" },
      { locale: "de", name: "Libyen", description: "Staat Libyen" },
      { locale: "it", name: "Libia", description: "Stato di Libia" },
    ],
  },
  {
    code: "MDG",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Madagascar",
        description: "Republic of Madagascar",
      },
      { locale: "ar", name: "مدغشقر", description: "جمهورية مدغشقر" },
      {
        locale: "es",
        name: "Madagascar",
        description: "República de Madagascar",
      },
      {
        locale: "fr",
        name: "Madagascar",
        description: "République de Madagascar",
      },
      {
        locale: "pt",
        name: "Madagascar",
        description: "República de Madagascar",
      },
      {
        locale: "ru",
        name: "Мадагаскар",
        description: "Республика Мадагаскар",
      },
      {
        locale: "de",
        name: "Madagaskar",
        description: "Republik Madagaskar",
      },
      {
        locale: "it",
        name: "Madagascar",
        description: "Repubblica del Madagascar",
      },
    ],
  },
  {
    code: "MWI",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Malawi", description: "Republic of Malawi" },
      { locale: "ar", name: "مالاوي", description: "جمهورية مالاوي" },
      { locale: "es", name: "Malaui", description: "República de Malaui" },
      { locale: "fr", name: "Malawi", description: "République du Malawi" },
      { locale: "pt", name: "Malawi", description: "República do Malawi" },
      { locale: "ru", name: "Малави", description: "Республика Малави" },
      { locale: "de", name: "Malawi", description: "Republik Malawi" },
      { locale: "it", name: "Malawi", description: "Repubblica del Malawi" },
    ],
  },
  {
    code: "MLI",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Mali", description: "Republic of Mali" },
      { locale: "ar", name: "مالي", description: "جمهورية مالي" },
      { locale: "es", name: "Malí", description: "República de Malí" },
      { locale: "fr", name: "Mali", description: "République du Mali" },
      { locale: "pt", name: "Mali", description: "República do Mali" },
      { locale: "ru", name: "Мали", description: "Республика Мали" },
      { locale: "de", name: "Mali", description: "Republik Mali" },
      { locale: "it", name: "Mali", description: "Repubblica del Mali" },
    ],
  },
  {
    code: "MRT",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Mauritania",
        description: "Islamic Republic of Mauritania",
      },
      {
        locale: "ar",
        name: "موريتانيا",
        description: "الجمهورية الإسلامية الموريتانية",
      },
      {
        locale: "es",
        name: "Mauritania",
        description: "República Islámica de Mauritania",
      },
      {
        locale: "fr",
        name: "Mauritanie",
        description: "République islamique de Mauritanie",
      },
      {
        locale: "pt",
        name: "Mauritânia",
        description: "República Islâmica da Mauritânia",
      },
      {
        locale: "ru",
        name: "Мавритания",
        description: "Исламская Республика Мавритания",
      },
      {
        locale: "de",
        name: "Mauretanien",
        description: "Islamische Republik Mauretanien",
      },
      {
        locale: "it",
        name: "Mauritania",
        description: "Repubblica Islamica di Mauritania",
      },
    ],
  },
  {
    code: "MUS",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Mauritius", description: "Republic of Mauritius" },
      { locale: "ar", name: "موريشيوس", description: "جمهورية موريشيوس" },
      { locale: "es", name: "Mauricio", description: "República de Mauricio" },
      { locale: "fr", name: "Maurice", description: "République de Maurice" },
      { locale: "pt", name: "Maurícia", description: "República de Maurícia" },
      { locale: "ru", name: "Маврикий", description: "Республика Маврикий" },
      { locale: "de", name: "Mauritius", description: "Republik Mauritius" },
      {
        locale: "it",
        name: "Mauritius",
        description: "Repubblica di Mauritius",
      },
    ],
  },
  {
    code: "MAR",
    continent: "Africa",
    region: "Northern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Morocco", description: "Kingdom of Morocco" },
      { locale: "ar", name: "المغرب", description: "المملكة المغربية" },
      { locale: "es", name: "Marruecos", description: "Reino de Marruecos" },
      { locale: "fr", name: "Maroc", description: "Royaume du Maroc" },
      { locale: "pt", name: "Marrocos", description: "Reino de Marrocos" },
      { locale: "ru", name: "Марокко", description: "Королевство Марокко" },
      { locale: "de", name: "Marokko", description: "Königreich Marokko" },
      { locale: "it", name: "Marocco", description: "Regno del Marocco" },
    ],
  },
  {
    code: "MOZ",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Mozambique",
        description: "Republic of Mozambique",
      },
      { locale: "ar", name: "موزمبيق", description: "جمهورية موزمبيق" },
      {
        locale: "es",
        name: "Mozambique",
        description: "República de Mozambique",
      },
      {
        locale: "fr",
        name: "Mozambique",
        description: "République du Mozambique",
      },
      {
        locale: "pt",
        name: "Moçambique",
        description: "República de Moçambique",
      },
      {
        locale: "ru",
        name: "Мозамбик",
        description: "Республика Мозамбик",
      },
      {
        locale: "de",
        name: "Mosambik",
        description: "Republik Mosambik",
      },
      {
        locale: "it",
        name: "Mozambico",
        description: "Repubblica del Mozambico",
      },
    ],
  },
  {
    code: "NAM",
    continent: "Africa",
    region: "Southern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Namibia", description: "Republic of Namibia" },
      { locale: "ar", name: "ناميبيا", description: "جمهورية ناميبيا" },
      { locale: "es", name: "Namibia", description: "República de Namibia" },
      { locale: "fr", name: "Namibie", description: "République de Namibie" },
      { locale: "pt", name: "Namíbia", description: "República da Namíbia" },
      { locale: "ru", name: "Намибия", description: "Республика Намибия" },
      { locale: "de", name: "Namibia", description: "Republik Namibia" },
      {
        locale: "it",
        name: "Namibia",
        description: "Repubblica della Namibia",
      },
    ],
  },
  {
    code: "NER",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Niger", description: "Republic of the Niger" },
      { locale: "ar", name: "النيجر", description: "جمهورية النيجر" },
      { locale: "es", name: "Níger", description: "República del Níger" },
      { locale: "fr", name: "Niger", description: "République du Niger" },
      { locale: "pt", name: "Níger", description: "República do Níger" },
      { locale: "ru", name: "Нигер", description: "Республика Нигер" },
      { locale: "de", name: "Niger", description: "Republik Niger" },
      { locale: "it", name: "Niger", description: "Repubblica del Niger" },
    ],
  },
  {
    code: "NGA",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Nigeria",
        description: "Federal Republic of Nigeria",
      },
      {
        locale: "ar",
        name: "نيجيريا",
        description: "جمهورية نيجيريا الاتحادية",
      },
      {
        locale: "es",
        name: "Nigeria",
        description: "República Federal de Nigeria",
      },
      {
        locale: "fr",
        name: "Nigéria",
        description: "République fédérale du Nigéria",
      },
      {
        locale: "pt",
        name: "Nigéria",
        description: "República Federal da Nigéria",
      },
      {
        locale: "ru",
        name: "Нигерия",
        description: "Федеративная Республика Нигерия",
      },
      {
        locale: "de",
        name: "Nigeria",
        description: "Bundesrepublik Nigeria",
      },
      {
        locale: "it",
        name: "Nigeria",
        description: "Repubblica Federale di Nigeria",
      },
    ],
  },
  {
    code: "RWA",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Rwanda", description: "Republic of Rwanda" },
      { locale: "ar", name: "رواندا", description: "جمهورية رواندا" },
      { locale: "es", name: "Ruanda", description: "República de Ruanda" },
      { locale: "fr", name: "Rwanda", description: "République du Rwanda" },
      { locale: "pt", name: "Ruanda", description: "República do Ruanda" },
      { locale: "ru", name: "Руанда", description: "Республика Руанда" },
      { locale: "de", name: "Ruanda", description: "Republik Ruanda" },
      { locale: "it", name: "Ruanda", description: "Repubblica del Ruanda" },
    ],
  },
  {
    code: "STP",
    continent: "Africa",
    region: "Middle Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "São Tomé and Príncipe",
        description: "Democratic Republic of São Tomé and Príncipe",
      },
      {
        locale: "ar",
        name: "ساو تومي وبرينسيبي",
        description: "جمهورية ساو تومي وبرينسيبي الديمقراطية",
      },
      {
        locale: "es",
        name: "Santo Tomé y Príncipe",
        description: "República Democrática de Santo Tomé y Príncipe",
      },
      {
        locale: "fr",
        name: "Sao Tomé-et-Principe",
        description: "République démocratique de Sao Tomé-et-Principe",
      },
      {
        locale: "pt",
        name: "São Tomé e Príncipe",
        description: "República Democrática de São Tomé e Príncipe",
      },
      {
        locale: "ru",
        name: "Сан-Томе и Принсипи",
        description: "Демократическая Республика Сан-Томе и Принсипи",
      },
      {
        locale: "de",
        name: "São Tomé und Príncipe",
        description: "Demokratische Republik São Tomé und Príncipe",
      },
      {
        locale: "it",
        name: "São Tomé e Príncipe",
        description: "Repubblica Democratica di São Tomé e Príncipe",
      },
    ],
  },
  {
    code: "SEN",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Senegal", description: "Republic of Senegal" },
      { locale: "ar", name: "السنغال", description: "جمهورية السنغال" },
      { locale: "es", name: "Senegal", description: "República de Senegal" },
      { locale: "fr", name: "Sénégal", description: "République du Sénégal" },
      { locale: "pt", name: "Senegal", description: "República do Senegal" },
      { locale: "ru", name: "Сенегал", description: "Республика Сенегал" },
      { locale: "de", name: "Senegal", description: "Republik Senegal" },
      { locale: "it", name: "Senegal", description: "Repubblica del Senegal" },
    ],
  },
  {
    code: "SYC",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Seychelles",
        description: "Republic of Seychelles",
      },
      { locale: "ar", name: "سيشل", description: "جمهورية سيشل" },
      {
        locale: "es",
        name: "Seychelles",
        description: "República de Seychelles",
      },
      {
        locale: "fr",
        name: "Seychelles",
        description: "République des Seychelles",
      },
      {
        locale: "pt",
        name: "Seychelles",
        description: "República das Seychelles",
      },
      {
        locale: "ru",
        name: "Сейшельские Острова",
        description: "Республика Сейшельские Острова",
      },
      {
        locale: "de",
        name: "Seychellen",
        description: "Republik Seychellen",
      },
      {
        locale: "it",
        name: "Seychelles",
        description: "Repubblica delle Seychelles",
      },
    ],
  },
  {
    code: "SLE",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Sierra Leone",
        description: "Republic of Sierra Leone",
      },
      { locale: "ar", name: "سيراليون", description: "جمهورية سيراليون" },
      {
        locale: "es",
        name: "Sierra Leona",
        description: "República de Sierra Leona",
      },
      {
        locale: "fr",
        name: "Sierra Leone",
        description: "République de Sierra Leone",
      },
      {
        locale: "pt",
        name: "Serra Leoa",
        description: "República da Serra Leoa",
      },
      {
        locale: "ru",
        name: "Сьерра-Леоне",
        description: "Республика Сьерра-Леоне",
      },
      {
        locale: "de",
        name: "Sierra Leone",
        description: "Republik Sierra Leone",
      },
      {
        locale: "it",
        name: "Sierra Leone",
        description: "Repubblica della Sierra Leone",
      },
    ],
  },
  {
    code: "SOM",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Somalia",
        description: "Federal Republic of Somalia",
      },
      {
        locale: "ar",
        name: "الصومال",
        description: "جمهورية الصومال الفيدرالية",
      },
      {
        locale: "es",
        name: "Somalia",
        description: "República Federal de Somalia",
      },
      {
        locale: "fr",
        name: "Somalie",
        description: "République fédérale de Somalie",
      },
      {
        locale: "pt",
        name: "Somália",
        description: "República Federal da Somália",
      },
      {
        locale: "ru",
        name: "Сомали",
        description: "Федеративная Республика Сомали",
      },
      {
        locale: "de",
        name: "Somalia",
        description: "Bundesrepublik Somalia",
      },
      {
        locale: "it",
        name: "Somalia",
        description: "Repubblica Federale di Somalia",
      },
    ],
  },
  {
    code: "ZAF",
    continent: "Africa",
    region: "Southern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "South Africa",
        description: "Republic of South Africa",
      },
      {
        locale: "ar",
        name: "جنوب أفريقيا",
        description: "جمهورية جنوب أفريقيا",
      },
      {
        locale: "es",
        name: "Sudáfrica",
        description: "República de Sudáfrica",
      },
      {
        locale: "fr",
        name: "Afrique du Sud",
        description: "République d'Afrique du Sud",
      },
      {
        locale: "pt",
        name: "África do Sul",
        description: "República da África do Sul",
      },
      {
        locale: "ru",
        name: "Южная Африка",
        description: "Южно-Африканская Республика",
      },
      {
        locale: "de",
        name: "Südafrika",
        description: "Republik Südafrika",
      },
      {
        locale: "it",
        name: "Sudafrica",
        description: "Repubblica del Sudafrica",
      },
    ],
  },
  {
    code: "SSD",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "South Sudan",
        description: "Republic of South Sudan",
      },
      {
        locale: "ar",
        name: "جنوب السودان",
        description: "جمهورية جنوب السودان",
      },
      {
        locale: "es",
        name: "Sudán del Sur",
        description: "República de Sudán del Sur",
      },
      {
        locale: "fr",
        name: "Soudan du Sud",
        description: "République du Soudan du Sud",
      },
      {
        locale: "pt",
        name: "Sudão do Sul",
        description: "República do Sudão do Sul",
      },
      {
        locale: "ru",
        name: "Южный Судан",
        description: "Республика Южный Судан",
      },
      {
        locale: "de",
        name: "Südsudan",
        description: "Republik Südsudan",
      },
      {
        locale: "it",
        name: "Sudan del Sud",
        description: "Repubblica del Sudan del Sud",
      },
    ],
  },
  {
    code: "SDN",
    continent: "Africa",
    region: "Northern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Sudan", description: "Republic of the Sudan" },
      { locale: "ar", name: "السودان", description: "جمهورية السودان" },
      { locale: "es", name: "Sudán", description: "República del Sudán" },
      { locale: "fr", name: "Soudan", description: "République du Soudan" },
      { locale: "pt", name: "Sudão", description: "República do Sudão" },
      { locale: "ru", name: "Судан", description: "Республика Судан" },
      { locale: "de", name: "Sudan", description: "Republik Sudan" },
      { locale: "it", name: "Sudan", description: "Repubblica del Sudan" },
    ],
  },
  {
    code: "TZA",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      {
        locale: "en",
        name: "Tanzania",
        description: "United Republic of Tanzania",
      },
      {
        locale: "ar",
        name: "تنزانيا",
        description: "جمهورية تنزانيا الاتحادية",
      },
      {
        locale: "es",
        name: "Tanzania",
        description: "República Unida de Tanzania",
      },
      {
        locale: "fr",
        name: "Tanzanie",
        description: "République unie de Tanzanie",
      },
      {
        locale: "pt",
        name: "Tanzânia",
        description: "República Unida da Tanzânia",
      },
      {
        locale: "ru",
        name: "Танзания",
        description: "Объединённая Республика Танзания",
      },
      {
        locale: "de",
        name: "Tansania",
        description: "Vereinigte Republik Tansania",
      },
      {
        locale: "it",
        name: "Tanzania",
        description: "Repubblica Unita di Tanzania",
      },
    ],
  },
  {
    code: "TGO",
    continent: "Africa",
    region: "Western Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Togo", description: "Togolese Republic" },
      { locale: "ar", name: "توغو", description: "جمهورية توغو" },
      { locale: "es", name: "Togo", description: "República Togolesa" },
      { locale: "fr", name: "Togo", description: "République togolaise" },
      { locale: "pt", name: "Togo", description: "República Togolesa" },
      { locale: "ru", name: "Того", description: "Тоголезская Республика" },
      { locale: "de", name: "Togo", description: "Republik Togo" },
      { locale: "it", name: "Togo", description: "Repubblica Togolese" },
    ],
  },
  {
    code: "TUN",
    continent: "Africa",
    region: "Northern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Tunisia", description: "Republic of Tunisia" },
      { locale: "ar", name: "تونس", description: "الجمهورية التونسية" },
      { locale: "es", name: "Túnez", description: "República de Túnez" },
      { locale: "fr", name: "Tunisie", description: "République tunisienne" },
      { locale: "pt", name: "Tunísia", description: "República da Tunísia" },
      { locale: "ru", name: "Тунис", description: "Тунисская Республика" },
      { locale: "de", name: "Tunesien", description: "Republik Tunesien" },
      { locale: "it", name: "Tunisia", description: "Repubblica Tunisina" },
    ],
  },
  {
    code: "UGA",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Uganda", description: "Republic of Uganda" },
      { locale: "ar", name: "أوغندا", description: "جمهورية أوغندا" },
      { locale: "es", name: "Uganda", description: "República de Uganda" },
      { locale: "fr", name: "Ouganda", description: "République d'Ouganda" },
      { locale: "pt", name: "Uganda", description: "República do Uganda" },
      { locale: "ru", name: "Уганда", description: "Республика Уганда" },
      { locale: "de", name: "Uganda", description: "Republik Uganda" },
      { locale: "it", name: "Uganda", description: "Repubblica dell'Uganda" },
    ],
  },
  {
    code: "ZMB",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Zambia", description: "Republic of Zambia" },
      { locale: "ar", name: "زامبيا", description: "جمهورية زامبيا" },
      { locale: "es", name: "Zambia", description: "República de Zambia" },
      { locale: "fr", name: "Zambie", description: "République de Zambie" },
      { locale: "pt", name: "Zâmbia", description: "República da Zâmbia" },
      { locale: "ru", name: "Замбия", description: "Республика Замбия" },
      { locale: "de", name: "Sambia", description: "Republik Sambia" },
      { locale: "it", name: "Zambia", description: "Repubblica dello Zambia" },
    ],
  },
  {
    code: "ZWE",
    continent: "Africa",
    region: "Eastern Africa",
    isActive: true,
    translations: [
      { locale: "en", name: "Zimbabwe", description: "Republic of Zimbabwe" },
      { locale: "ar", name: "زيمبابوي", description: "جمهورية زيمبابوي" },
      { locale: "es", name: "Zimbabue", description: "República de Zimbabue" },
      { locale: "fr", name: "Zimbabwe", description: "République du Zimbabwe" },
      { locale: "pt", name: "Zimbabué", description: "República do Zimbabué" },
      { locale: "ru", name: "Зимбабве", description: "Республика Зимбабве" },
      { locale: "de", name: "Simbabwe", description: "Republik Simbabwe" },
      {
        locale: "it",
        name: "Zimbabwe",
        description: "Repubblica dello Zimbabwe",
      },
    ],
  },
];
