name: Code checks

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: ["type-check", "lint", "test:ci"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}

      - name: Upload coverage reports to Codecov
        if: matrix.script == 'test:ci'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
